window.GenkiExercises = [
  // Lesson 0
  'lesson-0/hiragana-1|Hiragana|p.20-21',
  'lesson-0/hiragana-2|Hiragana: Diacritical Marks|p.21',
  'lesson-0/hiragana-3|Hiragana: Combos|p.21-22',
  'lesson-0/katakana-1|Katakana|p.24',
  'lesson-0/katakana-2|Katakana: Diacritical Marks|p.25',
  'lesson-0/katakana-3|Katakana: Combos|p.25',
  'lesson-0/katakana-4|Katakana: Additional Combos|p.26',
  'lesson-0/kana-match|Bonus: Match Hiragana and Katakana|p.20-21 & 24',
  'lesson-0/greetings|Greetings 1|p.32',
  'lesson-0/greetings-2|Greetings 2|p.32',
  'lesson-0/culture-1|Culture Note: Greetings and Bowing|p.32',
  'lesson-0/greetings-practice|Practice: Greetings|p.34',
  'lesson-0/numbers-1|Vocabulary: Numbers 0-14|p.35',
  'lesson-0/numbers-2|Vocabulary: Numbers 15-100|p.35',
  'lesson-0/numbers-3|Practice: Reading Numbers 1|p.35; A',
  'lesson-0/numbers-4|Practice: Reading Numbers 2|p.35; B',
  'lesson-0/numbers-5|Practice: Reading Numbers 3|p.35; C',
  'lesson-0/workbook-1|Workbook: Greetings|p.13-14',
  'lesson-0/workbook-2|Workbook: Numbers|p.15',
  
  // Lesson 1
  'lesson-1/vocab-1|Vocabulary: School|p.38',
  'lesson-1/vocab-2|Vocabulary: People and Time|p.38',
  'lesson-1/vocab-3|Vocabulary: Others and Expressions|p.38-39',
  'lesson-1/vocab-4|Vocabulary: Countries|p.39',
  'lesson-1/vocab-5|Vocabulary: Majors|p.39',
  'lesson-1/vocab-6|Vocabulary: Occupations|p.39-40',
  'lesson-1/vocab-7|Vocabulary: Family|p.40',
  'lesson-1/culture-1|Culture Note: Japanese Names|p.45',
  'lesson-1/grammar-1|Practice: XはYです 1 (Nationality)|p.46; I-A',
  'lesson-1/vocab-8|Practice Vocabulary: Year in School|p.46',
  'lesson-1/grammar-2|Practice: XはYです 2 (Year in School)|p.46; I-B',
  'lesson-1/vocab-9|Practice Vocabulary: Age|p.47',
  'lesson-1/grammar-3|Practice: XはYです 3 (Age)|p.47; I-C',
  'lesson-1/grammar-4|Practice: Question Sentences 1|p.47-48; II-A',
  'lesson-1/grammar-5|Practice: Question Sentences 2|p.48; II-B',
  'lesson-1/grammar-6|Practice: Question Sentences 3|p.49; II-C',
  'lesson-1/grammar-7|Practice: NounのNoun 1|p.50; III-A',
  'lesson-1/grammar-8|Practice: NounのNoun 2|p.50; III-B',
  'lesson-1/grammar-9|Practice: NounのNoun 3|p.51; III-C',
  'lesson-1/grammar-10|Practice: Telephone Numbers|p.51; IV',
  'lesson-1/vocab-10|Practice Vocabulary: Time (Hours)|p.52',
  'lesson-1/grammar-11|Practice: Time 1|p.52; V-A',
  'lesson-1/grammar-12|Practice: Time 2|p.53; V-C',
  'lesson-1/vocab-11|Useful Expressions: Time (Minutes 1-10)|p.55',
  'lesson-1/vocab-12|Useful Expressions: Time (Minutes 11-30)|p.55',
  'lesson-1/workbook-1|Workbook: XはYです|p.16; I & II',
  'lesson-1/workbook-2|Workbook: Question Sentences|p.17; I & II',
  'lesson-1/workbook-3|Workbook: NounのNoun|p.18; I & II',
  'lesson-1/workbook-4|Workbook: Time and Telephone Numbers|p.19; I & II',
  'lesson-1/workbook-5|Workbook: Questions|p.20',
  'lesson-1/workbook-6|Workbook: Listening Comprehension 1|p.21; A',
  'lesson-1/workbook-7|Workbook: Listening Comprehension 2|p.22; B, C, & D',
  'lesson-1/literacy-1|Hiragana Practice: Identifying Hiragana|p.297; I-A',
  'lesson-1/literacy-2|Hiragana Practice: Word Match|p.297; I-B',
  'lesson-1/literacy-3|Hiragana Practice: Diacritical Marks|p.297; I-C',
  'lesson-1/literacy-4|Hiragana Practice: Combos and Double Consonants|p.298; I-D',
  'lesson-1/literacy-5|Hiragana Practice: Long Vowels|p.298; I-E',
  'lesson-1/literacy-6|Hiragana Practice: Unscramble the Words|p.298; I-F',
  'lesson-1/literacy-7|Reading Practice: Hiragana|p.299; II',
  'lesson-1/literacy-wb-1|Workbook: Hiragana (あ-こ)|p.121; I, II, & III',
  'lesson-1/literacy-wb-2|Workbook: Hiragana (さ-と)|p.122; I, II, & III',
  'lesson-1/literacy-wb-3|Workbook: Hiragana (な-ほ)|p.123; I, II, & III',
  'lesson-1/literacy-wb-4|Workbook: Hiragana (ま-よ)|p.124; I, II, & III',
  'lesson-1/literacy-wb-5|Workbook: Hiragana (ら-ん)|p.125; I, II, & III',
  'lesson-1/literacy-wb-6|Workbook: Hiragana (Dots/Circles/Small や, ゆ, よ)|p.126; I, II, III, & IV',
  'lesson-1/literacy-wb-7|Workbook: Hiragana (Double Consonants/Long Vowels)|p.127; I, II, III, & IV',
  
  // Lesson 2
  'lesson-2/vocab-1|Vocabulary: Words that Point|p.58',
  'lesson-2/vocab-2|Vocabulary: Food|p.58',
  'lesson-2/vocab-3|Vocabulary: Things|p.58-59',
  'lesson-2/vocab-4|Vocabulary: Places and Countries|p.59',
  'lesson-2/vocab-5|Vocabulary: Majors and Family|p.59',
  'lesson-2/vocab-6|Vocabulary: Money Matters and Expressions|p.59',
  'lesson-2/culture-1|Culture Note: Japanese Currency|p.66',
  'lesson-2/vocab-7|Practice Vocabulary: Numbers (Hundreds)|p.67',
  'lesson-2/vocab-8|Practice Vocabulary: Numbers (Thousands)|p.67',
  'lesson-2/vocab-9|Practice Vocabulary: Numbers (Ten Thousands)|p.67',
  'lesson-2/grammar-1|Practice: Numbers|p.67; I-A',
  'lesson-2/grammar-2|Practice: Prices|p.67-68; I-B',
  'lesson-2/grammar-3|Practice: これ／それ|p.69; II-A',
  'lesson-2/grammar-4|Practice: あれ|p.70; II-B',
  'lesson-2/grammar-5|Practice: この／その／あの|p.70-71; III-A',
  'lesson-2/grammar-6|Practice: どこ|p.72; IV',
  'lesson-2/grammar-7|Practice: ここ／そこ／あそこ|p.72; IV',
  'lesson-2/grammar-8|Practice: だれのNoun|p.73; V',
  'lesson-2/grammar-9|Practice: Nounも|p.73-74; VI',
  'lesson-2/grammar-10|Practice: Nounじゃないです|p.74-75; VII-A',
  'lesson-2/vocab-10|Bonus Vocabulary: Food|p.76',
  'lesson-2/vocab-11|Useful Expressions: Classroom Objects|p.81',
  'lesson-2/vocab-12|Useful Expressions: In the Classroom|p.81',
  'lesson-2/workbook-1|Workbook: Numbers|p.25; I, II, & III',
  'lesson-2/workbook-2|Workbook: これ／それ／あれ|p.26; I & II',
  'lesson-2/workbook-3|Workbook: この／その／あの|p.27',
  'lesson-2/workbook-4|Workbook: ここ／そこ／あそこ・だれの|p.28; I & II',
  'lesson-2/workbook-5|Workbook: Nounも・Nounじゃないです|p.29; I & II',
  'lesson-2/workbook-6|Workbook: Questions|p.30',
  'lesson-2/workbook-7|Workbook: Listening Comprehension|p.31; A, B, & C',
  'lesson-2/literacy-1|Katakana Practice: Identifying Katakana|p.301; I-A',
  'lesson-2/literacy-2|Katakana Practice: Word Match|p.301; I-B',
  'lesson-2/literacy-3|Katakana Practice: Countries and Capitals|p.302; I-C',
  'lesson-2/literacy-4|Katakana Practice: Unscramble the Words|p.302; I-D',
  'lesson-2/literacy-5|Reading Practice: Katakana|p.302-303; II',
  'lesson-2/literacy-wb-1|Workbook: Katakana (ア-コ)|p.128; I & II',
  'lesson-2/literacy-wb-2|Workbook: Katakana (サ-ト)|p.129; I & II',
  'lesson-2/literacy-wb-3|Workbook: Katakana (ナ-ホ)|p.130; I & II',
  'lesson-2/literacy-wb-4|Workbook: Katakana (マ-ヨ)|p.131; I & II',
  'lesson-2/literacy-wb-5|Workbook: Katakana (ラ-ン)|p.132; I & II',
  
  // Lesson 3
  'lesson-3/vocab-1|Vocabulary: Entertainment and Sports|p.84',
  'lesson-3/vocab-2|Vocabulary: Foods and Drinks|p.84',
  'lesson-3/vocab-3|Vocabulary: Places and Time|p.84-85',
  'lesson-3/vocab-4|Vocabulary: U-verbs|p.85',
  'lesson-3/vocab-5|Vocabulary: Ru-verbs and Irregular Verbs|p.85',
  'lesson-3/vocab-6|Vocabulary: Adverbs|p.85',
  'lesson-3/vocab-7|Vocabulary: Adjectives and Expressions|p.85',
  'lesson-3/grammar-0|Review: Identifying Verbs|p.86-88',
  'lesson-3/grammar-1|Practice: Verb Conjugation|p.94; I',
  'lesson-3/grammar-2|Practice: を Particle|p.95; II-A; a',
  'lesson-3/grammar-3|Practice: で Particle|p.95; II-A; b',
  'lesson-3/grammar-4|Practice: を and で Particles|p.95; II-B',
  'lesson-3/grammar-5|Practice: に Particle|p.96; III-A',
  'lesson-3/grammar-6|Practice: Time References 1|p.97; IV-A',
  'lesson-3/grammar-7|Practice: Time References 2|p.98; IV-D',
  'lesson-3/grammar-8|Practice: Suggestion Using ～ませんか|p.98; V-A',
  'lesson-3/grammar-9|Practice: Frequency Adverbs|p.99; VI',
  'lesson-3/culture-1|Culture Note: Japanese Houses|p.101',
  'lesson-3/workbook-1|Workbook: Verb Conjugation|p.32',
  'lesson-3/workbook-2|Workbook: NounをVerb|p.33',
  'lesson-3/workbook-3|Workbook: Verbs with Places|p.34; I &amp; II',
  'lesson-3/workbook-4|Workbook: Time References|p.35; I, II, &amp; III',
  'lesson-3/workbook-5|Workbook: Suggestion Using ～ませんか|p.36; I &amp; II',
  'lesson-3/workbook-6|Workbook: Frequency Adverbs|p.37',
  'lesson-3/workbook-7|Workbook: Questions|p.38',
  'lesson-3/workbook-8|Workbook: Listening Comprehension 1|p.39; A & B',
  'lesson-3/workbook-9|Workbook: Listening Comprehension 2|p.40; C & D',
  'lesson-3/literacy-1|Kanji Practice: Readings|p.304-305',
  'lesson-3/literacy-2|Kanji Practice: Meanings|p.304-305',
  'lesson-3/literacy-3|Kanji Practice: Stroke Order|p.304-305',
  'lesson-3/literacy-4|Kanji Vocabulary: 一, 二, and 三|p.304',
  'lesson-3/literacy-5|Kanji Vocabulary: 四, 五, and 六|p.304',
  'lesson-3/literacy-6|Kanji Vocabulary: 七, 八, and 九|p.304-305',
  'lesson-3/literacy-7|Kanji Vocabulary: 十, 百, and 千|p.305',
  'lesson-3/literacy-8|Kanji Vocabulary: 万, 円, and 時|p.305',
  'lesson-3/literacy-9|Kanji Practice: Prices|p.306; I-A & B',
  'lesson-3/literacy-10|Reading Practice: まいにちのせいかつ|p.307; II',
  'lesson-3/literacy-wb-1|Workbook: Kanji Writing Practice|p.133',
  'lesson-3/literacy-wb-2|Workbook: Using Kanji|p.134; I, II, & III',

  // Lesson 4
  'lesson-4/vocab-1|Vocabulary: People and Things|p.104',
  'lesson-4/vocab-2|Vocabulary: Activities and Places|p.104',
  'lesson-4/vocab-3|Vocabulary: Time|p.105',
  'lesson-4/vocab-4|Vocabulary: U-verbs and Ru-verbs|p.105',
  'lesson-4/vocab-5|Vocabulary: Adverbs and Expressions|p.105',
  'lesson-4/vocab-6|Vocabulary: Location Words|p.106',
  'lesson-4/culture-1|Culture Note: Japanese National Holidays|p.114',
  'lesson-4/grammar-1|Practice: Xがあります／います|p.115; I-A',
  'lesson-4/grammar-2|Practice: Xがあります|p.116; I-C',
  'lesson-4/grammar-3|Practice: Describing Where Things Are 1|p.117; II-A',
  'lesson-4/grammar-4|Practice: Describing Where Things Are 2|p.117; II-B',
  'lesson-4/grammar-5|Practice: Past Tense of です|p.118; III-A',
  'lesson-4/grammar-6|Practice: Verb Conjugation (Past Tense)|p.120; IV-A',
  'lesson-4/grammar-7|Practice: Past Tense of Verbs 1|p.120; IV-B',
  'lesson-4/grammar-8|Practice: Past Tense of Verbs 2|p.121; IV-C',
  'lesson-4/grammar-9|Practice: Past Tense of Verbs 3|p.121; IV-D',
  'lesson-4/grammar-10|Practice: も 1|p.122; V-A',
  'lesson-4/grammar-11|Practice: も 2|p.122-123; V-B',
  'lesson-4/grammar-12|Practice: ～時間|p.123; VI-A',
  'lesson-4/vocab-7|Useful Expressions: Days (1-15)|p.127',
  'lesson-4/vocab-8|Useful Expressions: Days (16-31)|p.127',
  'lesson-4/vocab-9|Useful Expressions: Months|p.127',
  'lesson-4/vocab-10|Useful Expressions: Time Words (Day and Week)|p.127',
  'lesson-4/vocab-11|Useful Expressions: Time Words (Month and Year)|p.127',
  'lesson-4/workbook-1|Workbook: Xがあります／います|p.41; I & II',
  'lesson-4/workbook-2|Workbook: Describing Where Things Are|p.42; I & II',
  'lesson-4/workbook-3|Workbook: Past Tense (Nouns)|p.43; I & II',
  'lesson-4/workbook-4|Workbook: Verb Conjugation (Past Tense)|p.44',
  'lesson-4/workbook-5|Workbook: Past Tense (Verbs)|p.45; I & II',
  'lesson-4/workbook-6|Workbook: も|p.46',
  'lesson-4/workbook-7|Workbook: ～時間・Particles|p.47; I & II',
  'lesson-4/workbook-8|Workbook: Questions|p.48',
  'lesson-4/workbook-9|Workbook: Listening Comprehension|p.49; A, B, &amp; C',
  'lesson-4/literacy-1|Kanji Practice: Readings|p.308-309',
  'lesson-4/literacy-2|Kanji Practice: Meanings|p.308-309',
  'lesson-4/literacy-3|Kanji Practice: Stroke Order|p.308-309',
  'lesson-4/literacy-4|Kanji Vocabulary: 日, 本, and 人|p.308',
  'lesson-4/literacy-5|Kanji Vocabulary: 月 and 火|p.308',
  'lesson-4/literacy-6|Kanji Vocabulary: 水, 木, and 金|p.308',
  'lesson-4/literacy-7|Kanji Vocabulary: 土, 曜, and 上|p.309',
  'lesson-4/literacy-8|Kanji Vocabulary: 下, 中, and 半|p.309',
  'lesson-4/literacy-9|Kanji Practice: Days of the Week|p.310; I-A',
  'lesson-4/literacy-10|Kanji Practice: Location Words|p.310; I-B',
  'lesson-4/literacy-11|Reading Practice: おかあさんへのメモ|p.310; II',
  'lesson-4/literacy-12|Reading Practice: メアリーさんのしゅうまつ|p.311; III',
  'lesson-4/literacy-wb-1|Workbook: Kanji Writing Practice|p.135',
  'lesson-4/literacy-wb-2|Workbook: Using Kanji|p.136; I, II, & III',
  
  // Lesson 5
  'lesson-5/vocab-1|Vocabulary: Nouns|p.130',
  'lesson-5/vocab-2|Vocabulary: い-adjectives|p.130-131',
  'lesson-5/vocab-3|Vocabulary: な-adjectives|p.131',
  'lesson-5/vocab-4|Vocabulary: U-verbs and Ru-verbs|p.131',
  'lesson-5/vocab-5|Vocabulary: Adverbs and Other Expressions|p.131',
  'lesson-5/grammar-1|Practice: Adjective Conjugation (Present Affirmative)|p.138; I-A',
  'lesson-5/grammar-2|Practice: Adjective Conjugation (Present Negative)|p.139; I-B',
  'lesson-5/grammar-3|Practice: Adjectives (Present Tense) 1|p.139; I-C',
  'lesson-5/grammar-4|Practice: Adjectives (Present Tense) 2|p.139; I-D',
  'lesson-5/grammar-5|Practice: Adjective Conjugation (Past Affirmative)|p.140; II-A',
  'lesson-5/grammar-6|Practice: Adjective Conjugation (Past Negative)|p.140; II-B',
  'lesson-5/grammar-7|Practice: Adjectives (Past Tense) 1|p.140; II-C',
  'lesson-5/grammar-8|Practice: Adjectives (Past Tense) 2|p.141; II-D',
  'lesson-5/grammar-9|Practice: Adjectives (Noun Modification) 1|p.141; III-A',
  'lesson-5/grammar-10|Practice: Adjectives (Noun Modification) 2|p.142; III-B',
  'lesson-5/grammar-11|Practice: 好き(な)／きらい(な) 1|p.142; IV-A',
  'lesson-5/grammar-12|Practice: 好き(な)／きらい(な) 2|p.143; IV-B',
  'lesson-5/grammar-13|Practice: ～ましょう|p.143; V-A',
  'lesson-5/culture-1|Culture Note: Japanese Festivals|p.145',
  'lesson-5/workbook-1|Workbook: Adjective Conjugation (Present Tense)|p.50',
  'lesson-5/workbook-2|Workbook: Adjectives (Present Tense)|p.51; I & II',
  'lesson-5/workbook-3|Workbook: Adjective Conjugation (Present and Past Tenses)|p.52',
  'lesson-5/workbook-4|Workbook: Adjectives (Past Tense)|p.53; I & II',
  'lesson-5/workbook-5|Workbook: Adjective + Noun|p.54; I & II',
  'lesson-5/workbook-6|Workbook: 好き(な)／きらい(な)|p.55',
  'lesson-5/workbook-7|Workbook: ～ましょう／～ましょうか|p.56; I & II',
  'lesson-5/workbook-8|Workbook: Questions|p.57; I & II',
  'lesson-5/workbook-9|Workbook: Listening Comprehension|p.58; A, B, & C',
  'lesson-5/literacy-1|Kanji Practice: Readings|p.312-313',
  'lesson-5/literacy-2|Kanji Practice: Meanings|p.312-313',
  'lesson-5/literacy-3|Kanji Practice: Stroke Order|p.312-313',
  'lesson-5/literacy-4|Kanji Vocabulary: 山, 川, and 元|p.312',
  'lesson-5/literacy-5|Kanji Vocabulary: 気, 天, and 私|p.312',
  'lesson-5/literacy-6|Kanji Vocabulary: 今, 田, and 女|p.312-313',
  'lesson-5/literacy-7|Kanji Vocabulary: 男, 見, and 行|p.313',
  'lesson-5/literacy-8|Kanji Vocabulary: 食 and 飲|p.313',
  'lesson-5/literacy-9|Kanji Practice: Match the Sentences|p.314; I-B',
  'lesson-5/literacy-10|Kanji Practice: Match the Readings|p.314; I-C',
  'lesson-5/literacy-11|Katakana Practice: Match the Words|p.315; II-A',
  'lesson-5/literacy-12|Reading Practice: Moe\'s Trip to Vienna|p.315; II-B',
  'lesson-5/literacy-13|Reading Practice: Robert\'s Postcard|p.316; II-C',
  'lesson-5/literacy-wb-1|Workbook: Kanji Writing Practice|p.137',
  'lesson-5/literacy-wb-2|Workbook: Using Kanji|p.138; I & II',
  
  // Lesson 6
  'lesson-6/vocab-1|Vocabulary: Nouns 1|p.148',
  'lesson-6/vocab-2|Vocabulary: Nouns 2 and な-adjectives|p.148',
  'lesson-6/vocab-3|Vocabulary: U-verbs|p.148-149',
  'lesson-6/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.149',
  'lesson-6/vocab-5|Vocabulary: Adverbs and Other Expressions|p.149',
  'lesson-6/grammar-0|Review: Te-form Conjugation Rules|p.150-151',
  'lesson-6/culture-1|Culture Note: Japan\'s Educational System (1)|p.154-155',
  'lesson-6/grammar-1|Practice: Te-form Conjugation|p.156; I-A',
  'lesson-6/grammar-2|Practice: ～てください 1|p.156-157; II-A',
  'lesson-6/grammar-3|Practice: ～てください 2|p.157; II-B',
  'lesson-6/grammar-4|Practice: Describing Two Activities 1|p.158; III-A',
  'lesson-6/grammar-5|Practice: Describing Two Activities 2|p.158; III-B',
  'lesson-6/grammar-6|Practice: ～てもいいです 1|p.159; IV-A',
  'lesson-6/grammar-7|Practice: ～てもいいです 2|p.160; IV-C',
  'lesson-6/grammar-8|Practice: ～てはいけません 1|p.160; V-A',
  'lesson-6/grammar-9|Practice: ～てはいけません 2|p.161; V-B',
  'lesson-6/grammar-10|Practice: ～から|p.161; VI-A',
  'lesson-6/grammar-11|Practice: ～ましょうか 1|p.162; VII-A',
  'lesson-6/grammar-12|Practice: ～ましょうか 2|p.163; VII-B',
  'lesson-6/vocab-6|Useful Expressions: Directions|p.165',
  'lesson-6/workbook-1|Workbook: Te-form Conjugation 1|p.59-60',
  'lesson-6/workbook-2|Workbook: Te-form Conjugation 2|p.61',
  'lesson-6/workbook-3|Workbook: ～てください|p.62; I & II',
  'lesson-6/workbook-4|Workbook: Describing Two Activities|p.63; I & II',
  'lesson-6/workbook-5|Workbook: ～てもいいです|p.64',
  'lesson-6/workbook-6|Workbook: ～てはいけません|p.65; I & II',
  'lesson-6/workbook-7|Workbook: ～から・～ましょうか|p.66; I & II',
  'lesson-6/workbook-8|Workbook: Questions|p.67',
  'lesson-6/workbook-9|Workbook: Listening Comprehension|p.68; A, B, & C',
  'lesson-6/literacy-1|Kanji Practice: Readings|p.318-319',
  'lesson-6/literacy-2|Kanji Practice: Meanings|p.318-319',
  'lesson-6/literacy-3|Kanji Practice: Stroke Order|p.318-319',
  'lesson-6/literacy-4|Kanji Vocabulary: 東, 西, and 南|p.318',
  'lesson-6/literacy-5|Kanji Vocabulary: 北, 口, and 出|p.318',
  'lesson-6/literacy-6|Kanji Vocabulary: 右, 左, and 分|p.318-319',
  'lesson-6/literacy-7|Kanji Vocabulary: 先, 生, and 大|p.319',
  'lesson-6/literacy-8|Kanji Vocabulary: 学, 外, and 国|p.319',
  'lesson-6/literacy-9|Kanji Practice: Combine the Kanji|p.320; I-A',
  'lesson-6/literacy-10|Kanji Practice: Find the Location|p.320; I-B',
  'lesson-6/literacy-11|Reading Practice: Bulletin Board|p.320-321; II',
  'lesson-6/literacy-12|Reading Practice: 私のすきなレストラン|p.322-323; III-A, B, & C',
  'lesson-6/literacy-wb-1|Workbook: Kanji Writing Practice|p.139',
  'lesson-6/literacy-wb-2|Workbook: Using Kanji|p.140; I & II',
  
  // Lesson 7
  'lesson-7/vocab-1|Vocabulary: Nouns 1|p.168',
  'lesson-7/vocab-2|Vocabulary: Nouns 2|p.168',
  'lesson-7/vocab-3|Vocabulary: い-adjectives and な-adjectives|p.168-169',
  'lesson-7/vocab-4|Vocabulary: U-verbs, Ru-verbs, and Irregular Verbs|p.169',
  'lesson-7/vocab-5|Vocabulary: Adverbs and Other Expressions|p.169',
  'lesson-7/vocab-6|Bonus Vocabulary: Counting People|p.174',
  'lesson-7/grammar-1|Practice: ～ている (Actions in Progress)|p.176; I-A',
  'lesson-7/grammar-2|Practice: ～ている (Result of a Change)|p.177; II-A',
  'lesson-7/grammar-3|Practice: Describing People 1|p.178; III-A',
  'lesson-7/grammar-4|Practice: Describing People 2|p.178; III-B',
  'lesson-7/grammar-5|Practice: Adjective/Noun Te-forms 1|p.179; IV-A',
  'lesson-7/grammar-6|Practice: Adjective/Noun Te-forms 2|p.180; IV-C',
  'lesson-7/grammar-7|Practice: Verb Stem + に行く／来る／帰る 1|p.181; V-A',
  'lesson-7/grammar-8|Practice: Verb Stem + に行く／来る／帰る 2|p.182; V-C',
  'lesson-7/grammar-9|Practice: Counting People|p.182; VI-A',
  'lesson-7/culture-1|Culture Note: Kinship Terms 1|p.184',
  'lesson-7/culture-2|Culture Note: Kinship Terms 2|p.184',
  'lesson-7/vocab-7|Useful Expressions: Parts of the Body|p.185',
  'lesson-7/workbook-1|Workbook: Te-form Conjugation|p.69',
  'lesson-7/workbook-2|Workbook: ～ている (Actions in Progress)|p.70; I, II, & III',
  'lesson-7/workbook-3|Workbook: ～ている (Result of a Change)|p.71; I & II',
  'lesson-7/workbook-4|Workbook: Describing People|p.72; I & II',
  'lesson-7/workbook-5|Workbook: Adjective/Noun Te-forms|p.73; I & II',
  'lesson-7/workbook-6|Workbook: Verb Stem + に行く／来る／帰る|p.74; I & II',
  'lesson-7/workbook-7|Workbook: Counting People|p.75; I & II',
  'lesson-7/workbook-8|Workbook: Questions|p.76',
  'lesson-7/workbook-9|Workbook: Listening Comprehension|p.77; A, B, & C',
  'lesson-7/literacy-1|Kanji Practice: Readings|p.324-325',
  'lesson-7/literacy-2|Kanji Practice: Meanings|p.324-325',
  'lesson-7/literacy-3|Kanji Practice: Stroke Order|p.324-325',
  'lesson-7/literacy-4|Kanji Vocabulary: 京, 子, and 小|p.324',
  'lesson-7/literacy-5|Kanji Vocabulary: 会, 社, and 父|p.324',
  'lesson-7/literacy-6|Kanji Vocabulary: 母, 高, and 校|p.324-325',
  'lesson-7/literacy-7|Kanji Vocabulary: 毎, 語, and 文|p.325',
  'lesson-7/literacy-8|Kanji Vocabulary: 帰 and 入|p.325',
  'lesson-7/literacy-9|Kanji Practice: Fill in the Blanks|p.326; I-A',
  'lesson-7/literacy-10|Kanji Practice: Word Search|p.326; I-C',
  'lesson-7/literacy-11|Reading Practice: メアリーさんのてがみ|p.327-328; II',
  'lesson-7/literacy-wb-1|Workbook: Kanji Writing Practice|p.141',
  'lesson-7/literacy-wb-2|Workbook: Using Kanji|p.142; I & II',
  
  // Lesson 8
  'lesson-8/vocab-1|Vocabulary: Nouns 1|p.188',
  'lesson-8/vocab-2|Vocabulary: Nouns 2|p.188',
  'lesson-8/vocab-3|Vocabulary: な-adjectives and U-verbs|p.188-189',
  'lesson-8/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.189',
  'lesson-8/vocab-5|Vocabulary: Adverbs and Other Expressions|p.189',
  'lesson-8/grammar-0|Review: Short Form Conjugation Rules|p.190-191',
  'lesson-8/grammar-1|Practice: Short Form Conjugation (Verbs)|p.198; I-A',
  'lesson-8/grammar-2|Practice: Short Form Conjugation (Adjectives/Nouns)|p.198; I-B',
  'lesson-8/grammar-3|Practice: Informal Speech (Verbs)|p.198-199; II-A',
  'lesson-8/grammar-4|Practice: Informal Speech (Adjectives/Nouns)|p.199; II-B',
  'lesson-8/grammar-5|Practice: Quotations (～と思います) 1|p.199; III-A',
  'lesson-8/grammar-6|Practice: Quotations (～と思います) 2|p.200; III-B',
  'lesson-8/grammar-7|Practice: Quotations (～と言っていました)|p.201; IV-A',
  'lesson-8/grammar-8|Practice: ～ないでください|p.202; V-A',
  'lesson-8/grammar-9|Practice: Verbのが上手です|p.203; VI-A',
  'lesson-8/grammar-10|Practice: が|p.204; VII-A',
  'lesson-8/grammar-11|Practice: 何も|p.204; VIII-A',
  'lesson-8/vocab-6|Culture Note: Common Dishes in Japan|p.208',
  'lesson-8/culture-1|Culture Note: Foods in Japan|p.208',
  'lesson-8/vocab-7|Useful Expressions: At the Supermarket|p.209',
  'lesson-8/vocab-8|Useful Expressions: Supermarket Foods|p.209',
  'lesson-8/workbook-1|Workbook: Short Form Conjugation (Present Tense)|p.78',
  'lesson-8/workbook-2|Workbook: Short Forms (Informal Speech)|p.79; I & II',
  'lesson-8/workbook-3|Workbook: Quotations (～と思います)|p.80; I & II',
  'lesson-8/workbook-4|Workbook: Quotations (～と言っていました)|p.81',
  'lesson-8/workbook-5|Workbook: ～ないでください|p.82; I & II',
  'lesson-8/workbook-6|Workbook: Verbのが好きです／上手です|p.83; I & II',
  'lesson-8/workbook-7|Workbook: が・何か and 何も|p.84; I & II',
  'lesson-8/workbook-8|Workbook: Questions|p.85; I & II',
  'lesson-8/workbook-9|Workbook: Listening Comprehension|p.86; A, B, & C',
  'lesson-8/literacy-1|Kanji Practice: Readings|p.329-330',
  'lesson-8/literacy-2|Kanji Practice: Meanings|p.329-330',
  'lesson-8/literacy-3|Kanji Practice: Stroke Order|p.329-330',
  'lesson-8/literacy-4|Kanji Vocabulary: 員, 新, and 聞|p.329',
  'lesson-8/literacy-5|Kanji Vocabulary: 作, 仕, and 事|p.329',
  'lesson-8/literacy-6|Kanji Vocabulary: 電 and 車|p.329',
  'lesson-8/literacy-7|Kanji Vocabulary: 休, 言, and 読|p.330',
  'lesson-8/literacy-8|Kanji Vocabulary: 思, 次, and 何|p.330',
  'lesson-8/literacy-9|Kanji Practice: Match the Verbs|p.331; I-B',
  'lesson-8/literacy-10|Reading Practice: 日本の会社員|p.332-333; II-C',
  'lesson-8/literacy-wb-1|Workbook: Kanji Writing Practice|p.143',
  'lesson-8/literacy-wb-2|Workbook: Using Kanji|p.144; I & II',
  
  // Lesson 9
  'lesson-9/vocab-1|Vocabulary: Nouns 1|p.212',
  'lesson-9/vocab-2|Vocabulary: Nouns 2|p.212',
  'lesson-9/vocab-3|Vocabulary: い-adjectives and な-adjectives|p.212',
  'lesson-9/vocab-4|Vocabulary: U-verbs, Ru-verbs, and Irregular Verbs|p.213',
  'lesson-9/vocab-5|Vocabulary: Adverbs and Other Expressions|p.213',
  'lesson-9/vocab-6|Vocabulary: Numbers (used to count small items)|p.213',
  'lesson-9/grammar-0|Review: Short Form Conjugation Rules (Past Tense)|p.214',
  'lesson-9/grammar-1|Practice: Short Form Conjugation (Past Tense Verbs)|p.219; I-A',
  'lesson-9/grammar-2|Practice: Short Form Conjugation (Past Tense Adjectives/Nouns)|p.219-220; I-B',
  'lesson-9/grammar-3|Practice: Informal Speech (Past Tense Verbs)|p.220; II-A',
  'lesson-9/grammar-4|Practice: Informal Speech (Past Tense Adjectives/Nouns)|p.220-221; II-B',
  'lesson-9/grammar-5|Practice: Quotations (～と思います)|p.221; III-A',
  'lesson-9/grammar-6|Practice: Quotations (～と言っていました)|p.222; IV-A',
  'lesson-9/grammar-7|Practice: Qualifying Nouns with Verbs|p.223; V-A',
  'lesson-9/grammar-8|Practice: もう～ました／まだ～ていません|p.224; VI-A',
  'lesson-9/grammar-9|Practice: ～から|p.225; VII-A',
  'lesson-9/culture-1|Culture Note: Japanese Traditional Culture|p.228',
  'lesson-9/vocab-7|Useful Expressions: Color Names|p.229',
  'lesson-9/vocab-8|Useful Expressions: Colors|p.229',
  'lesson-9/workbook-1|Workbook: Past Tense Short Forms|p.87',
  'lesson-9/workbook-2|Workbook: Past Tense Short Forms (Informal Speech)|p.88; I & II',
  'lesson-9/workbook-3|Workbook: Quotations (～と思います)|p.89; I & II',
  'lesson-9/workbook-4|Workbook: Quotations (～と言っていました)|p.90',
  'lesson-9/workbook-5|Workbook: Qualifying Nouns with Verbs|p.91',
  'lesson-9/workbook-6|Workbook: もう～ました／まだ～ていません|p.92',
  'lesson-9/workbook-7|Workbook: ～から|p.93; I & II',
  'lesson-9/workbook-8|Workbook: Questions|p.94',
  'lesson-9/workbook-9|Workbook: Listening Comprehension|p.95; A, B, & C',
  'lesson-9/literacy-1|Kanji Practice: Readings|p.334-335',
  'lesson-9/literacy-2|Kanji Practice: Meanings|p.334-335',
  'lesson-9/literacy-3|Kanji Practice: Stroke Order|p.334-335',
  'lesson-9/literacy-4|Kanji Vocabulary: 午, 後, and 前|p.334',
  'lesson-9/literacy-5|Kanji Vocabulary: 名, 白, and 雨|p.334',
  'lesson-9/literacy-6|Kanji Vocabulary: 書, 友, and 間|p.334-335',
  'lesson-9/literacy-7|Kanji Vocabulary: 家, 話, and 少|p.335',
  'lesson-9/literacy-8|Kanji Vocabulary: 古, 知, and 来|p.335',
  'lesson-9/literacy-9|Kanji Practice: Fill in the Blanks|p.336; I-A & B',
  'lesson-9/literacy-10|Reading Practice: ソラさんの日記|p.336-338; II-A, B, & C',
  'lesson-9/vocab-9|Useful Expressions: for Mail/Letters|p.339',
  'lesson-9/literacy-wb-1|Workbook: Kanji Writing Practice|p.145',
  'lesson-9/literacy-wb-2|Workbook: Using Kanji|p.146; I & II',
  
  // Lesson 10
  'lesson-10/vocab-1|Vocabulary: Nouns 1|p.232',
  'lesson-10/vocab-2|Vocabulary: Nouns 2|p.232',
  'lesson-10/vocab-3|Vocabulary: い-adjectives and な-adjectives|p.233',
  'lesson-10/vocab-4|Vocabulary: U-verbs, Ru-verbs, and Irregular Verbs|p.233',
  'lesson-10/vocab-5|Vocabulary: Adverbs and Other Expressions|p.233',
  'lesson-10/grammar-1|Practice: Comparison between Two Items|p.239; I-A',
  'lesson-10/grammar-2|Practice: Comparison among Three or More Items|p.240; II-A',
  'lesson-10/grammar-3|Practice: Adjective/Noun + の 1|p.242; III-A',
  'lesson-10/grammar-4|Practice: Adjective/Noun + の 2|p.242; III-B',
  'lesson-10/grammar-5|Practice: ～つもりだ|p.243; IV-A',
  'lesson-10/grammar-6|Practice: Adjective + なる 1|p.244-245; V-A',
  'lesson-10/grammar-7|Practice: Adjective + なる 2|p.245; V-B',
  'lesson-10/grammar-8|Practice: どこかに／どこにも|p.246; VI-A',
  'lesson-10/grammar-9|Practice: ～で行きます|p.247; VII-A',
  'lesson-10/grammar-10|Practice: ～かかります|p.247; VII-B',
  'lesson-10/culture-1|Culture Note: Public Transportation in Japan|p.251',
  'lesson-10/vocab-6|Useful Expressions: At the Station 1|p.252',
  'lesson-10/vocab-7|Useful Expressions: At the Station 2|p.252',
  'lesson-10/vocab-8|Useful Expressions: At the Station 3|p.253',
  'lesson-10/workbook-1|Workbook: Comparison between Two Items|p.96; I & II',
  'lesson-10/workbook-2|Workbook: Comparison among Three or More Items|p.97; I & II',
  'lesson-10/workbook-3|Workbook: Adjective/Noun + の|p.98; I & II',
  'lesson-10/workbook-4|Workbook: ～つもりだ|p.99; I & II',
  'lesson-10/workbook-5|Workbook: Adjective + なる|p.100; I & II',
  'lesson-10/workbook-6|Workbook: どこかに／どこにも・～で行きます|p.101; I & II',
  'lesson-10/workbook-7|Workbook: Questions|p.102',
  'lesson-10/workbook-8|Workbook: Listening Comprehension|p.103-104; A, B, & C',
  'lesson-10/literacy-1|Kanji Practice: Readings|p.340-341',
  'lesson-10/literacy-2|Kanji Practice: Meanings|p.340-341',
  'lesson-10/literacy-3|Kanji Practice: Stroke Order|p.340-341',
  'lesson-10/literacy-4|Kanji Vocabulary: 住, 正, and 年|p.340',
  'lesson-10/literacy-5|Kanji Vocabulary: 売, 買, and 町|p.340',
  'lesson-10/literacy-6|Kanji Vocabulary: 長, 道, and 雪|p.340-341',
  'lesson-10/literacy-7|Kanji Vocabulary: 立, 自, and 夜|p.341',
  'lesson-10/literacy-8|Kanji Vocabulary: 朝 and 持|p.341',
  'lesson-10/literacy-9|Kanji Practice: Antonyms|p.342; I-B',
  'lesson-10/literacy-10|Kanji Practice: Fill in the Blanks|p.342; I-C',
  'lesson-10/literacy-11|Reading Practice: かさじぞう|p.343-345; II-B, C, & D',
  'lesson-10/literacy-wb-1|Workbook: Kanji Writing Practice|p.147',
  'lesson-10/literacy-wb-2|Workbook: Using Kanji|p.148; I & II',
  
  // Lesson 11
  'lesson-11/vocab-1|Vocabulary: Nouns 1|p.256',
  'lesson-11/vocab-2|Vocabulary: Nouns 2|p.256',
  'lesson-11/vocab-3|Vocabulary: U-verbs, Ru-verbs, and Irregular Verbs|p.256-257',
  'lesson-11/vocab-4|Vocabulary: Adverbs and Other Expressions|p.257',
  'lesson-11/vocab-5|Vocabulary: Occupations|p.257',
  'lesson-11/grammar-1|Practice: ～たい|p.264; I-A',
  'lesson-11/grammar-2|Practice: ～たい (Past Tense)|p.264; I-C',
  'lesson-11/grammar-3|Practice: ～たり～たりする|p.266; II-A',
  'lesson-11/grammar-4|Practice: ～ことがある|p.267; III-A',
  'lesson-11/grammar-5|Practice: Noun A や Noun B|p.268; IV',
  'lesson-11/culture-1|Culture Note: New Year\'s|p.270',
  'lesson-11/vocab-6|Useful Expressions: In Japanese Class|p.271',
  'lesson-11/vocab-7|Useful Expressions: Japanese Class Vocabulary 1|p.271',
  'lesson-11/vocab-8|Useful Expressions: Japanese Class Vocabulary 2|p.271',
  'lesson-11/workbook-1|Workbook: ～たい|p.105; I & II',
  'lesson-11/workbook-2|Workbook: ～たり～たりする|p.106; I & II',
  'lesson-11/workbook-3|Workbook: ～ことがある|p.107; I & II',
  'lesson-11/workbook-4|Workbook: Noun A や Noun B|p.108',
  'lesson-11/workbook-5|Workbook: Questions|p.109; I & II',
  'lesson-11/workbook-6|Workbook: Listening Comprehension|p.110; A, B, & C',
  'lesson-11/literacy-1|Kanji Practice: Readings|p.346-347',
  'lesson-11/literacy-2|Kanji Practice: Meanings|p.346-347',
  'lesson-11/literacy-3|Kanji Practice: Stroke Order|p.346-347',
  'lesson-11/literacy-4|Kanji Vocabulary: 手, 紙, and 好|p.346',
  'lesson-11/literacy-5|Kanji Vocabulary: 近, 明, 病, and 院|p.346',
  'lesson-11/literacy-6|Kanji Vocabulary: 映, 画, and 歌|p.346-347',
  'lesson-11/literacy-7|Kanji Vocabulary: 市, 所, and 勉|p.347',
  'lesson-11/literacy-8|Kanji Vocabulary: 強, 有, and 旅|p.347',
  'lesson-11/literacy-9|Kanji Practice: Compounds|p.348; I-B',
  'lesson-11/literacy-10|Reading Practice: 友だち・メンバー募集|p.348-351; II-B, C, D, & E',
  'lesson-11/literacy-wb-1|Workbook: Kanji Writing Practice|p.149',
  'lesson-11/literacy-wb-2|Workbook: Using Kanji|p.150; I & II',
  
  // Lesson 12
  'lesson-12/vocab-1|Vocabulary: Nouns 1|p.274',
  'lesson-12/vocab-2|Vocabulary: Nouns 2|p.274',
  'lesson-12/vocab-3|Vocabulary: い-adjectives and な-adjectives|p.274-275',
  'lesson-12/vocab-4|Vocabulary: U-verbs, Ru-verbs, and Irregular Verbs|p.275',
  'lesson-12/vocab-5|Vocabulary: Adverbs and Other Expressions|p.275',
  'lesson-12/grammar-1|Practice: ～んです 1|p.282; I-A',
  'lesson-12/grammar-2|Practice: ～んです 2|p.283; I-B',
  'lesson-12/grammar-3|Practice: ～すぎる|p.284-285; II-A',
  'lesson-12/grammar-4|Practice: ～ほうがいいです|p.285; III-A',
  'lesson-12/grammar-5|Practice: ～ので|p.287; IV-A',
  'lesson-12/grammar-6|Practice: ～なければいけません|p.288; V-A',
  'lesson-12/grammar-7|Practice: ～なきゃいけない|p.288; V-C',
  'lesson-12/grammar-8|Practice: ～でしょうか|p.289; VI-A',
  'lesson-12/culture-1|Culture Note: The Japanese Climate|p.292',
  'lesson-12/vocab-6|Useful Expressions: Health and Illness|p.293-294',
  'lesson-12/vocab-7|Useful Expressions: Doctor\'s Office Vocabulary|p.294',
  'lesson-12/workbook-1|Workbook: ～んです|p.111; I & II',
  'lesson-12/workbook-2|Workbook: ～すぎる|p.112; I & II',
  'lesson-12/workbook-3|Workbook: ～ほうがいいです|p.113; I & II',
  'lesson-12/workbook-4|Workbook: ～ので|p.114; I & II',
  'lesson-12/workbook-5|Workbook: ～なければいけません／なきゃいけません|p.115; I & II',
  'lesson-12/workbook-6|Workbook: ～でしょうか|p.116',
  'lesson-12/workbook-7|Workbook: Questions|p.117',
  'lesson-12/workbook-8|Workbook: Listening Comprehension|p.118; A, B, & C',
  'lesson-12/literacy-1|Kanji Practice: Readings|p.352-353',
  'lesson-12/literacy-2|Kanji Practice: Meanings|p.352-353',
  'lesson-12/literacy-3|Kanji Practice: Stroke Order|p.352-353',
  'lesson-12/literacy-4|Kanji Vocabulary: 昔, 々, and 神|p.352',
  'lesson-12/literacy-5|Kanji Vocabulary: 早, 起, and 牛|p.352',
  'lesson-12/literacy-6|Kanji Vocabulary: 使, 働, and 連|p.352-353',
  'lesson-12/literacy-7|Kanji Vocabulary: 別 and 度|p.353',
  'lesson-12/literacy-8|Kanji Vocabulary: 赤, 青, and 色|p.353',
  'lesson-12/literacy-9|Kanji Practice: Match the Readings|p.354; I-A',
  'lesson-12/literacy-10|Reading Practice: 七夕|p.355-356; II-B & C',
  'lesson-12/literacy-wb-1|Workbook: Kanji Writing Practice|p.151',
  'lesson-12/literacy-wb-2|Workbook: Using Kanji|p.152; I & II',
  
  // Lesson 13
  'lesson-13/vocab-1|Vocabulary: Nouns 1|p.24',
  'lesson-13/vocab-2|Vocabulary: Nouns 2|p.24',
  'lesson-13/vocab-3|Vocabulary: い-adjectives and な-adjectives|p.24-25',
  'lesson-13/vocab-4|Vocabulary: U-verbs and Irregular Verbs|p.25',
  'lesson-13/vocab-5|Vocabulary: Adverbs and Other Expressions|p.25',
  'lesson-13/vocab-6|Vocabulary: Numbers Used to Count Days|p.25',
  'lesson-13/grammar-1|Practice: Potential Verbs 1|p.33; I-A',
  'lesson-13/grammar-2|Practice: Potential Verbs 2|p.33; I-B',
  'lesson-13/grammar-3|Practice: Potential Verbs 3|p.35; I-F',
  'lesson-13/grammar-4|Practice: ～し|p.35-36; II-A',
  'lesson-13/grammar-5|Practice: ～そうです 1|p.37; III-A',
  'lesson-13/grammar-6|Practice: ～そうです 2|p.37; III-B',
  'lesson-13/grammar-7|Practice: ～てみる|p.39; IV-A',
  'lesson-13/grammar-8|Practice: なら|p.40; V-A',
  'lesson-13/grammar-9|Practice: 一週間に三回|p.41; VI-A',
  'lesson-13/culture-1|Culture Note: Names of Years|p.44',
  'lesson-13/culture-2|Culture Note: East Asian Zodiacs|p.44',
  'lesson-13/vocab-7|Useful Expressions: Bank Words|p.45',
  'lesson-13/vocab-8|Useful Expressions: At the Bank|p.45',
  'lesson-13/workbook-1|Workbook: Potential Verbs Conjugation|p.11; I',
  'lesson-13/workbook-2|Workbook: Potential Verbs 1|p.12; II',
  'lesson-13/workbook-3|Workbook: Potential Verbs 2|p.13; I & II',
  'lesson-13/workbook-4|Workbook: ～し|p.14; I & II',
  'lesson-13/workbook-5|Workbook: ～そうです|p.15; I & II',
  'lesson-13/workbook-6|Workbook: ～てみる|p.16; I & II',
  'lesson-13/workbook-7|Workbook: なら|p.17; I & II',
  'lesson-13/workbook-8|Workbook: 一週間に三回|p.18; I & II',
  'lesson-13/workbook-9|Workbook: Questions|p.19; I & II',
  'lesson-13/workbook-10|Workbook: Listening Comprehension|p.20; A, B, & C',
  'lesson-13/literacy-1|Kanji Practice: Readings|p.274-275',
  'lesson-13/literacy-2|Kanji Practice: Meanings|p.274-275',
  'lesson-13/literacy-3|Kanji Practice: Stroke Order|p.274-275',
  'lesson-13/literacy-4|Kanji Vocabulary: 物, 鳥, and 料|p.274',
  'lesson-13/literacy-5|Kanji Vocabulary: 理, 特, and 安|p.274',
  'lesson-13/literacy-6|Kanji Vocabulary: 飯, 肉, and 悪|p.274-275',
  'lesson-13/literacy-7|Kanji Vocabulary: 体, 同, 着, and 空|p.275',
  'lesson-13/literacy-8|Kanji Vocabulary: 港, 昼, and 海|p.275',
  'lesson-13/literacy-9|Kanji Practice: Write the Readings|p.276; I-A & B',
  'lesson-13/literacy-10|Reading Practice: Identify the Food|p.277; II-A',
  'lesson-13/literacy-11|Reading Practice: 日本のおもしろい経験|p.277-278; II-B & C',
  'lesson-13/literacy-12|Reading Practice: 留学生座談会|p.279-280; III-B & C',
  'lesson-13/literacy-wb-1|Workbook: Kanji Writing Practice|p.111',
  'lesson-13/literacy-wb-2|Workbook: Using Kanji|p.112',
  
  // Lesson 14
  'lesson-14/vocab-1|Vocabulary: Nouns 1|p.48',
  'lesson-14/vocab-2|Vocabulary: Nouns 2|p.48',
  'lesson-14/vocab-3|Vocabulary: Adjectives and Verbs|p.48-49',
  'lesson-14/vocab-4|Vocabulary: Adverbs and Other Expressions|p.49',
  'lesson-14/vocab-5|Vocabulary: Counters|p.49',
  'lesson-14/grammar-1|Practice: ほしい (Present)|p.57; I-A',
  'lesson-14/grammar-2|Practice: ほしい (Past)|p.57; I-B',
  'lesson-14/grammar-3|Practice: ～かもしれません|p.59; II-A',
  'lesson-14/grammar-4|Practice: あげる|p.61; III-A',
  'lesson-14/grammar-5|Practice: くれる／もらう|p.62; III-C',
  'lesson-14/grammar-6|Practice: あげる／くれる／もらう|p.62; III-D',
  'lesson-14/grammar-7|Practice: ～たらどうですか|p.64; IV-A',
  'lesson-14/grammar-8|Practice: Counters|p.65; V-A',
  'lesson-14/grammar-9|Practice: Number+も／Number+しか+Negative|p.65-66; V-B',
  'lesson-14/culture-1|Culture Note: Annual Events in Japan|p.68',
  'lesson-14/vocab-6|Useful Expressions: Counters|p.69',
  'lesson-14/workbook-1|Workbook: ほしい|p.21; I, II, & III',
  'lesson-14/workbook-2|Workbook: ～かもしれません|p.22; I & II',
  'lesson-14/workbook-3|Workbook: あげる／くれる／もらう|p.23; I & II',
  'lesson-14/workbook-4|Workbook: ～たらどうですか|p.24; I & II',
  'lesson-14/workbook-5|Workbook: Number+も／Number+しか+Negative|p.25; I & II',
  'lesson-14/workbook-6|Workbook: Questions|p.26; I & II',
  'lesson-14/workbook-7|Workbook: Listening Comprehension|p.27; A, B, & C',
  'lesson-14/literacy-1|Kanji Practice: Readings|p.281-282',
  'lesson-14/literacy-2|Kanji Practice: Meanings|p.281-282',
  'lesson-14/literacy-3|Kanji Practice: Stroke Order|p.281-282',
  'lesson-14/literacy-4|Kanji Vocabulary: 彼, 代, and 留|p.281',
  'lesson-14/literacy-5|Kanji Vocabulary: 族, 親, and 切|p.281',
  'lesson-14/literacy-6|Kanji Vocabulary: 英, 店, and 去|p.281-282',
  'lesson-14/literacy-7|Kanji Vocabulary: 急, 乗, and 当|p.282',
  'lesson-14/literacy-8|Kanji Vocabulary: 音, 楽, 医, and 者|p.282',
  'lesson-14/literacy-9|Kanji Practice: Write the Readings|p.283; I-A & B',
  'lesson-14/literacy-10|Reading Practice: 悩みの相談|p.284-285; II-B & C',
  'lesson-14/literacy-wb-1|Workbook: Kanji Writing Practice|p.113',
  'lesson-14/literacy-wb-2|Workbook: Using Kanji|p.114',
  
  // Lesson 15
  'lesson-15/vocab-1|Vocabulary: Nouns 1|p.72',
  'lesson-15/vocab-2|Vocabulary: Nouns 2|p.72',
  'lesson-15/vocab-3|Vocabulary: U-verbs|p.72-73',
  'lesson-15/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.73',
  'lesson-15/vocab-5|Vocabulary: Adverbs and Other Expressions|p.73',
  'lesson-15/culture-1|Culture Note: Japanese Accommodations|p.77',
  'lesson-15/vocab-6|Bonus Vocabulary: ～目|p.79',
  'lesson-15/grammar-1|Practice: Volitional Form 1|p.80; I-A',
  'lesson-15/grammar-2|Practice: Volitional Form 2|p.80-81; I-B',
  'lesson-15/grammar-3|Practice: Volitional Form + と思っています|p.82; II-A',
  'lesson-15/grammar-4|Practice: ～ておく|p.83; III-A',
  'lesson-15/grammar-5|Practice: Using Sentences to Qualify Nouns 1|p.85; IV-A',
  'lesson-15/grammar-6|Practice: Using Sentences to Qualify Nouns 2|p.85-86; IV-B',
  'lesson-15/grammar-7|Practice: Using Sentences to Qualify Nouns 3|p.86-87; IV-D',
  'lesson-15/vocab-7|Useful Expressions: Hotel Vocab|p.91',
  'lesson-15/vocab-8|Useful Expressions: At the Hotel|p.91',
  'lesson-15/workbook-1|Workbook: Volitional Form Conjugation|p.28; I',
  'lesson-15/workbook-2|Workbook: Volitional Form Usage|p.28; II',
  'lesson-15/workbook-3|Workbook: Volitional Form + と思っています|p.29; I & II',
  'lesson-15/workbook-4|Workbook: ～ておく|p.30; I & II',
  'lesson-15/workbook-5|Workbook: Using Sentences to Qualify Nouns 1|p.31; I & II',
  'lesson-15/workbook-6|Workbook: Using Sentences to Qualify Nouns 2|p.32; I & II',
  'lesson-15/workbook-7|Workbook: Questions|p.33; I & II',
  'lesson-15/workbook-8|Workbook: Listening Comprehension|p.34; A, B, & C',
  'lesson-15/literacy-1|Kanji Practice: Readings|p.286-287',
  'lesson-15/literacy-2|Kanji Practice: Meanings|p.286-287',
  'lesson-15/literacy-3|Kanji Practice: Stroke Order|p.286-287',
  'lesson-15/literacy-4|Kanji Vocabulary: 死, 意, and 味|p.286',
  'lesson-15/literacy-5|Kanji Vocabulary: 注, 夏, 魚, and 寺|p.286',
  'lesson-15/literacy-6|Kanji Vocabulary: 広, 足, and 転|p.286-287',
  'lesson-15/literacy-7|Kanji Vocabulary: 借, 走, and 場|p.287',
  'lesson-15/literacy-8|Kanji Vocabulary: 建, 地, and 通|p.287',
  'lesson-15/literacy-9|Kanji Practice: Write the Readings|p.288; I-A & B',
  'lesson-15/literacy-10|Reading Practice: 私が好きな所|p.289-292; II-B, C, & D',
  'lesson-15/literacy-wb-1|Workbook: Kanji Writing Practice|p.115',
  'lesson-15/literacy-wb-2|Workbook: Using Kanji|p.116',
  
  // Lesson 16
  'lesson-16/vocab-1|Vocabulary: Nouns 1|p.94',
  'lesson-16/vocab-2|Vocabulary: Nouns 2 and い-adjectives|p.94',
  'lesson-16/vocab-3|Vocabulary: U-verbs|p.94-95',
  'lesson-16/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.95',
  'lesson-16/vocab-5|Vocabulary: Adverbs and Other Expressions|p.95',
  'lesson-16/culture-1|Culture Note: Gift-giving in Japan|p.103',
  'lesson-16/grammar-1|Practice: ～てあげる|p.104; I-A',
  'lesson-16/grammar-2|Practice: ～てくれる／～てもらう|p.105; I-C',
  'lesson-16/grammar-3|Practice: ～てあげる／～てくれる／～てもらう|p.105-106; I-E',
  'lesson-16/grammar-4|Practice: ～ていただけませんか|p.107-108; II-A',
  'lesson-16/grammar-5|Practice: ～といいですね|p.108-109; III-A',
  'lesson-16/grammar-6|Practice: ～時 1|p.110-111; IV-A',
  'lesson-16/grammar-7|Practice: ～時 2|p.111; IV-B',
  'lesson-16/grammar-8|Practice: ～てすみませんでした 1|p.112; V-A',
  'lesson-16/grammar-9|Practice: ～てすみませんでした 2|p.112; V-B',
  'lesson-16/workbook-1|Workbook: ～てあげる／～てくれる／～てもらう 1|p.35; I & II',
  'lesson-16/workbook-2|Workbook: ～てあげる／～てくれる／～てもらう 2|p.36; I & II',
  'lesson-16/workbook-3|Workbook: ～ていただけませんか|p.37; I & II',
  'lesson-16/workbook-4|Workbook: ～といいですね／～といいんですが|p.38; I & II',
  'lesson-16/workbook-5|Workbook: ～時 1|p.39; I & II',
  'lesson-16/workbook-6|Workbook: ～時 2|p.40; I & II',
  'lesson-16/workbook-7|Workbook: ～てすみませんでした|p.41; I & II',
  'lesson-16/workbook-8|Workbook: Questions|p.42; I & II',
  'lesson-16/workbook-9|Workbook: Listening Comprehension|p.43; A, B, & C',
  'lesson-16/literacy-1|Kanji Practice: Readings|p.293-294',
  'lesson-16/literacy-2|Kanji Practice: Meanings|p.293-294',
  'lesson-16/literacy-3|Kanji Practice: Stroke Order|p.293-294',
  'lesson-16/literacy-4|Kanji Vocabulary: 供, 世, 界, and 全|p.293',
  'lesson-16/literacy-5|Kanji Vocabulary: 部, 始, and 週|p.293',
  'lesson-16/literacy-6|Kanji Vocabulary: 考, 開, and 屋|p.293-294',
  'lesson-16/literacy-7|Kanji Vocabulary: 方, 運, and 動|p.294',
  'lesson-16/literacy-8|Kanji Vocabulary: 教, 室, and 以|p.294',
  'lesson-16/literacy-9|Kanji Practice: Write the Readings|p.295; I-A & B',
  'lesson-16/literacy-10|Reading Practice: まんが「ドラえもん」|p.296-298; II-B, C, & D',
  'lesson-16/literacy-wb-1|Workbook: Kanji Writing Practice|p.117',
  'lesson-16/literacy-wb-2|Workbook: Using Kanji|p.118',
  
  // Lesson 17
  'lesson-17/vocab-1|Vocabulary: Nouns 1|p.116',
  'lesson-17/vocab-2|Vocabulary: Nouns 2|p.116',
  'lesson-17/vocab-3|Vocabulary: Adjectives and U-verbs|p.116-117',
  'lesson-17/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.117',
  'lesson-17/vocab-5|Vocabulary: Adverbs and Other Expressions|p.117',
  'lesson-17/culture-1|Culture Note: Japanese Gestures|p.124',
  'lesson-17/grammar-1|Practice: ～そうです (I hear)|p.125; I-A',
  'lesson-17/grammar-2|Practice: ～って|p.126; II-A',
  'lesson-17/grammar-3|Practice: ～たら 1|p.127; III-A',
  'lesson-17/grammar-4|Practice: ～たら 2|p.127; III-B',
  'lesson-17/grammar-5|Practice: ～なくてもいいです|p.128-129; IV-A',
  'lesson-17/grammar-6|Practice: ～みたいです|p.130; V-A',
  'lesson-17/grammar-7|Practice: ～てから|p.132-133; VI-A',
  'lesson-17/grammar-8|Practice: ～前に|p.133; VI-B',
  'lesson-17/vocab-6|Useful Expressions: At the Hair Salon|p.135',
  'lesson-17/vocab-7|Useful Expressions: Hair Salon Words|p.135',
  'lesson-17/workbook-1|Workbook: ～そうです (I hear)／～って|p.44; I, II, & III',
  'lesson-17/workbook-2|Workbook: ～たら|p.45; I & II',
  'lesson-17/workbook-3|Workbook: ～なくてもいいです|p.46; I, II, & III',
  'lesson-17/workbook-4|Workbook: ～みたいです|p.47; I & II',
  'lesson-17/workbook-5|Workbook: ～前に／～てから|p.48; I & II',
  'lesson-17/workbook-6|Workbook: Questions|p.49; I & II',
  'lesson-17/workbook-7|Workbook: Listening Comprehension|p.50; A, B, & C',
  'lesson-17/literacy-1|Kanji Practice: Readings|p.299-300',
  'lesson-17/literacy-2|Kanji Practice: Meanings|p.299-300',
  'lesson-17/literacy-3|Kanji Practice: Stroke Order|p.299-300',
  'lesson-17/literacy-4|Kanji Vocabulary: 野, 習, and 主|p.299',
  'lesson-17/literacy-5|Kanji Vocabulary: 歳, 集, and 発|p.299',
  'lesson-17/literacy-6|Kanji Vocabulary: 表, 品, and 写|p.299-300',
  'lesson-17/literacy-7|Kanji Vocabulary: 真, 字, and 活|p.300',
  'lesson-17/literacy-8|Kanji Vocabulary: 結, 婚, and 歩|p.300',
  'lesson-17/literacy-9|Kanji Practice: Write the Readings|p.301; I-A &amp; B',
  'lesson-17/literacy-10|Reading Practice: オノ・ヨーコ|p.302-304; I-A, B, &amp; C',
  'lesson-17/literacy-wb-1|Workbook: Kanji Writing Practice|p.119',
  'lesson-17/literacy-wb-2|Workbook: Using Kanji|p.120',
  
  // Lesson 18
  'lesson-18/vocab-1|Vocabulary: Nouns 1|p.138',
  'lesson-18/vocab-2|Vocabulary: Nouns 2 and Adjectives|p.138',
  'lesson-18/vocab-3|Vocabulary: U-verbs|p.138-139',
  'lesson-18/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.139',
  'lesson-18/vocab-5|Vocabulary: Adverbs and Other Expressions|p.139',
  'lesson-18/vocab-6|Review: Transitivity Pairs|p.140',
  'lesson-18/grammar-1|Practice: Transitivity Pairs|p.146; I-A',
  'lesson-18/grammar-2|Practice: Paired Intransitive Verbs + ている|p.147-148; II-A',
  'lesson-18/grammar-3|Practice: ～てしまう 1|p.149; III-A',
  'lesson-18/grammar-4|Practice: ～てしまう 2|p.150; III-B',
  'lesson-18/grammar-5|Practice: ～ちゃう／～じゃう|p.150; III-C',
  'lesson-18/grammar-6|Practice: ～と|p.151; IV-A',
  'lesson-18/grammar-7|Practice: ～ながら|p.153; V-A',
  'lesson-18/grammar-8|Practice: ～ばよかったです Conjugation|p.154; VI-A',
  'lesson-18/grammar-9|Practice: ～ばよかったです|p.154-155; VI-B',
  'lesson-18/culture-1|Culture Note: Sushi|p.159',
  'lesson-18/culture-2|Culture Note: Popular Sushi Toppings|p.159',
  'lesson-18/workbook-0|Workbook: Transitivity Pairs 0|bonus exercise',
  'lesson-18/workbook-1|Workbook: Transitivity Pairs 1|p.51',
  'lesson-18/workbook-2|Workbook: Transitivity Pairs 2|p.52; I & II',
  'lesson-18/workbook-3|Workbook: Paired Intransitive Verbs + ている|p.53',
  'lesson-18/workbook-4|Workbook: ～てしまう|p.54; I & II',
  'lesson-18/workbook-5|Workbook: ～と|p.55; I, II, & III',
  'lesson-18/workbook-6|Workbook: ～ながら|p.56; I, II, & III',
  'lesson-18/workbook-7|Workbook: ～ばよかったです|p.57; I, II, & III',
  'lesson-18/workbook-8|Workbook: Questions|p.58; I & II',
  'lesson-18/workbook-9|Workbook: Listening Comprehension|p.59; A, B, & C',
  'lesson-18/literacy-1|Kanji Practice: Readings|p.306-307',
  'lesson-18/literacy-2|Kanji Practice: Meanings|p.306-307',
  'lesson-18/literacy-3|Kanji Practice: Stroke Order|p.306-307',
  'lesson-18/literacy-4|Kanji Vocabulary: 目, 的, and 洋|p.306',
  'lesson-18/literacy-5|Kanji Vocabulary: 服, 堂, 力, and 授|p.306',
  'lesson-18/literacy-6|Kanji Vocabulary: 業, 試, and 験|p.306-307',
  'lesson-18/literacy-7|Kanji Vocabulary: 貸, 図, and 館|p.307',
  'lesson-18/literacy-8|Kanji Vocabulary: 終, 宿, and 題|p.307',
  'lesson-18/literacy-9|Kanji Practice: Write the Readings|p.308; I-A & B',
  'lesson-18/literacy-10|Reading Practice: 大学生のアルバイト|p.308-309; II-B',
  'lesson-18/literacy-11|Reading Practice: 橋本くんの大学生活|p.310-311; III-A & B',
  'lesson-18/literacy-wb-1|Workbook: Kanji Writing Practice|p.121',
  'lesson-18/literacy-wb-2|Workbook: Using Kanji|p.122',
  
  // Lesson 19
  'lesson-19/vocab-1|Vocabulary: Nouns 1|p.162',
  'lesson-19/vocab-2|Vocabulary: Nouns 2 and Adjectives|p.162',
  'lesson-19/vocab-3|Vocabulary: U-verbs|p.162-163',
  'lesson-19/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.163',
  'lesson-19/vocab-5|Vocabulary: Adverbs and Other Expressions|p.163',
  'lesson-19/grammar-1|Practice: Honorific Verbs 1|p.170; I-A',
  'lesson-19/grammar-2|Practice: Honorific Verbs 2|p.170-171; I-B',
  'lesson-19/grammar-3|Practice: Honorific Verbs 3|p.171; I-C',
  'lesson-19/grammar-4|Practice: Giving Respectful Advice|p.172; II',
  'lesson-19/grammar-5|Practice: ～てくれてありがとう|p.173; III-A',
  'lesson-19/grammar-6|Practice: ～てよかったです|p.174; IV-A',
  'lesson-19/grammar-7|Practice: ～はずです 1|p.175; V-A',
  'lesson-19/grammar-8|Practice: ～はずです 2|p.176-177; V-C',
  'lesson-19/culture-1|Culture Note: Visiting Someone\'s House|p.179',
  'lesson-19/workbook-1|Workbook: Honorific Verbs 1|p.60',
  'lesson-19/workbook-2|Workbook: Honorific Verbs 2|p.61; I & II',
  'lesson-19/workbook-3|Workbook: Honorific Verbs 3・Giving Respectful Advice|p.62; I & II',
  'lesson-19/workbook-4|Workbook: ～てくれてありがとう|p.63; I & II',
  'lesson-19/workbook-5|Workbook: ～てよかったです|p.64; I & II',
  'lesson-19/workbook-6|Workbook: ～はずです|p.65; I, II, & III',
  'lesson-19/workbook-7|Workbook: Questions|p.66; I & II',
  'lesson-19/workbook-8|Workbook: Listening Comprehension|p.67-68; A, B, & C',
  'lesson-19/literacy-1|Kanji Practice: Readings|p.313-314',
  'lesson-19/literacy-2|Kanji Practice: Meanings|p.313-314',
  'lesson-19/literacy-3|Kanji Practice: Stroke Order|p.313-314',
  'lesson-19/literacy-4|Kanji Vocabulary: 春, 秋, and 冬|p.313',
  'lesson-19/literacy-5|Kanji Vocabulary: 花, 様, and 不|p.313',
  'lesson-19/literacy-6|Kanji Vocabulary: 姉, 兄, 漢, and 卒|p.313-314',
  'lesson-19/literacy-7|Kanji Vocabulary: 工, 研, and 究|p.314',
  'lesson-19/literacy-8|Kanji Vocabulary: 質, 問, and 多|p.314',
  'lesson-19/literacy-9|Kanji Practice: Write the Readings|p.315; I-A & B',
  'lesson-19/literacy-10|Reading Practice: お礼の手紙|p.316-317; II-A, B, & C',
  'lesson-19/literacy-11|Reading Practice: マリアさんのメール|p.318-319; II-A & B',
  'lesson-19/literacy-12|Useful Expressions: Greeting Cards|p.320',
  'lesson-19/literacy-wb-1|Workbook: Kanji Writing Practice|p.123',
  'lesson-19/literacy-wb-2|Workbook: Using Kanji|p.124',
  
  // Lesson 20
  'lesson-20/vocab-1|Vocabulary: Nouns 1|p.182',
  'lesson-20/vocab-2|Vocabulary: Nouns 2 and Adjectives|p.182',
  'lesson-20/vocab-3|Vocabulary: U-verbs|p.182-183',
  'lesson-20/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.183',
  'lesson-20/vocab-5|Vocabulary: Adverbs and Other Expressions|p.183',
  'lesson-20/grammar-1|Practice: Extra-modest Expressions 1|p.191; I-A',
  'lesson-20/grammar-2|Practice: Extra-modest Expressions 2|p.191; I-B',
  'lesson-20/grammar-3|Practice: Extra-modest Expressions 3|p.192; I-C',
  'lesson-20/grammar-4|Practice: Extra-modest Expressions 4|p.192; I-D',
  'lesson-20/grammar-5|Practice: Humble Expressions 1|p.193; II-A',
  'lesson-20/grammar-6|Practice: Humble Expressions 2|p.193-194; II-B',
  'lesson-20/grammar-7|Practice: Humble Expressions 3|p.195; II-D',
  'lesson-20/grammar-8|Practice: ～ないで|p.196; III-A',
  'lesson-20/grammar-9|Practice: Questions within Larger Sentences|p.197; IV-A',
  'lesson-20/grammar-10|Practice: Name という Item|p.198; V-A',
  'lesson-20/grammar-11|Practice: ～やすい／～にくい|p.199-200; VI-A',
  'lesson-20/culture-1|Culture Note: Japanese Pop Culture|p.205',
  'lesson-20/workbook-1|Workbook: Extra-modest Expressions|p.69',
  'lesson-20/workbook-2|Workbook: Humble Expressions 1|p.70',
  'lesson-20/workbook-3|Workbook: Humble Expressions 2|p.71; I & II',
  'lesson-20/workbook-4|Workbook: Three Types of Respect Language|p.72; I & II',
  'lesson-20/workbook-5|Workbook: ～ないで|p.73; I & II',
  'lesson-20/workbook-6|Workbook: Questions Within Larger Sentences|p.74; I & II',
  'lesson-20/workbook-7|Workbook: Name という Item|p.75; I & II',
  'lesson-20/workbook-8|Workbook: ～やすい／～にくい|p.76; I & II',
  'lesson-20/workbook-9|Workbook: Questions|p.77; I & II',
  'lesson-20/workbook-10|Workbook: Listening Comprehension|p.78; A, B, & C',
  'lesson-20/literacy-1|Kanji Practice: Readings|p.321-322',
  'lesson-20/literacy-2|Kanji Practice: Meanings|p.321-322',
  'lesson-20/literacy-3|Kanji Practice: Stroke Order|p.321-322',
  'lesson-20/literacy-4|Kanji Vocabulary: 皿, 声, and 茶|p.321',
  'lesson-20/literacy-5|Kanji Vocabulary: 止, 枚, and 両|p.321',
  'lesson-20/literacy-6|Kanji Vocabulary: 無, 払, and 心|p.321-322',
  'lesson-20/literacy-7|Kanji Vocabulary: 笑, 絶, and 対|p.322',
  'lesson-20/literacy-8|Kanji Vocabulary: 痛, 最, and 続|p.322',
  'lesson-20/literacy-9|Kanji Practice: Write the Readings|p.323; I-A & B',
  'lesson-20/literacy-10|Reading Practice: 猫の皿|p.325-326; II-B & C',
  'lesson-20/literacy-wb-1|Workbook: Kanji Writing Practice|p.125',
  'lesson-20/literacy-wb-2|Workbook: Using Kanji|p.126',
  
  // Lesson 21
  'lesson-21/vocab-1|Vocabulary: Nouns 1|p.208',
  'lesson-21/vocab-2|Vocabulary: Nouns 2 and Adjectives|p.208',
  'lesson-21/vocab-3|Vocabulary: U-verbs|p.208-209',
  'lesson-21/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.209',
  'lesson-21/vocab-5|Vocabulary: Adverbs and Other Expressions|p.209',
  'lesson-21/grammar-1|Practice: Passive Sentences 1|p.217; I-A',
  'lesson-21/grammar-2|Practice: Passive Sentences 2|p.217-218; I-B',
  'lesson-21/grammar-3|Practice: ～てある|p.219; II-A',
  'lesson-21/grammar-4|Practice: ～間に|p.221; III-A',
  'lesson-21/grammar-5|Practice: Adjective + する|p.222; IV-A',
  'lesson-21/grammar-6|Practice: ～てほしい|p.223; V-A',
  'lesson-21/culture-1|Culture Note: Religion in Japan|p.227',
  'lesson-21/culture-2|Culture Note: Shrine and Temple Words|p.227',
  'lesson-21/workbook-1|Workbook: Passive Sentences 1|p.79; I & II',
  'lesson-21/workbook-2|Workbook: Passive Sentences 2|p.80; I & II',
  'lesson-21/workbook-3|Workbook: Passive and ～てもらう|p.81',
  'lesson-21/workbook-4|Workbook: ～てある|p.82; I & II',
  'lesson-21/workbook-5|Workbook: ～間に|p.83; I & II',
  'lesson-21/workbook-6|Workbook: Adjective + する|p.84; I & II',
  'lesson-21/workbook-7|Workbook: ～てほしい|p.85',
  'lesson-21/workbook-8|Workbook: Questions|p.86; I & II',
  'lesson-21/workbook-9|Workbook: Listening Comprehension|p.87; A, B, & C',
  'lesson-21/literacy-1|Kanji Practice: Readings|p.328-329',
  'lesson-21/literacy-2|Kanji Practice: Meanings|p.328-329',
  'lesson-21/literacy-3|Kanji Practice: Stroke Order|p.328-329',
  'lesson-21/literacy-4|Kanji Vocabulary: 信, 経, and 台|p.328',
  'lesson-21/literacy-5|Kanji Vocabulary: 風, 犬, and 重|p.328',
  'lesson-21/literacy-6|Kanji Vocabulary: 初, 若, and 送|p.328-329',
  'lesson-21/literacy-7|Kanji Vocabulary: 幸, 計, and 遅|p.329',
  'lesson-21/literacy-8|Kanji Vocabulary: 配, 弟, and 妹|p.329',
  'lesson-21/literacy-9|Kanji Practice: Write the Readings|p.330; I-A & B',
  'lesson-21/literacy-10|Reading Practice: 厄年|p.331-333; II-B & C',
  'lesson-21/literacy-wb-1|Workbook: Kanji Writing Practice|p.127',
  'lesson-21/literacy-wb-2|Workbook: Using Kanji|p.128',

  // Lesson 22
  'lesson-22/vocab-1|Vocabulary: Nouns 1|p.230',
  'lesson-22/vocab-2|Vocabulary: Nouns 2|p.230',
  'lesson-22/vocab-3|Vocabulary: Adjectives and U-verbs|p.230-231',
  'lesson-22/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.231',
  'lesson-22/vocab-5|Vocabulary: Adverbs and Other Expressions|p.231',
  'lesson-22/grammar-1|Practice: Causative Sentences 1|p.238; I-A',
  'lesson-22/grammar-2|Practice: Causative Sentences 2|p.238-239; I-B',
  'lesson-22/grammar-3|Practice: Causative + てくれる|p.241; II-A',
  'lesson-22/grammar-4|Practice: Causative + てください|p.242; II-D',
  'lesson-22/grammar-5|Practice: Verb Stem + なさい|p.243; III-A',
  'lesson-22/grammar-6|Practice: ～ば|p.243; IV-A',
  'lesson-22/grammar-7|Practice: ～ば大丈夫です|p.244-245; IV-B',
  'lesson-22/grammar-8|Practice: ～のに|p.245; V-A',
  'lesson-22/grammar-9|Practice: ～のように|p.246; VI-A',
  'lesson-22/culture-1|Culture Note: Japan\'s Educational System (2)|p.249',
  'lesson-22/culture-2|Culture Note: Words for University and College Life|p.249',
  'lesson-22/workbook-1|Workbook: Causative Sentences 1|p.88; I & II',
  'lesson-22/workbook-2|Workbook: Causative Sentences 2|p.89',
  'lesson-22/workbook-3|Workbook: Causative + あげる／くれる|p.90; I & II',
  'lesson-22/workbook-4|Workbook: Verb Stem + なさい|p.91; I & II',
  'lesson-22/workbook-5|Workbook: ～ば|p.92; I, II, & III',
  'lesson-22/workbook-6|Workbook: ～のに|p.93; I & II',
  'lesson-22/workbook-7|Workbook: ～のように／～のような|p.94; I, II, & III',
  'lesson-22/workbook-8|Workbook: Questions|p.95; I & II',
  'lesson-22/workbook-9|Workbook: Listening Comprehension|p.96; A, B, & C',
  'lesson-22/literacy-1|Kanji Practice: Readings|p.334-335',
  'lesson-22/literacy-2|Kanji Practice: Meanings|p.334-335',
  'lesson-22/literacy-3|Kanji Practice: Stroke Order|p.334-335',
  'lesson-22/literacy-4|Kanji Vocabulary: 記, 銀, and 回|p.334',
  'lesson-22/literacy-5|Kanji Vocabulary: 夕, 黒, and 用|p.334',
  'lesson-22/literacy-6|Kanji Vocabulary: 末, 待, and 残|p.334-335',
  'lesson-22/literacy-7|Kanji Vocabulary: 駅, 番, and 説|p.335',
  'lesson-22/literacy-8|Kanji Vocabulary: 案, 内, 忘, and 守|p.335',
  'lesson-22/literacy-9|Kanji Practice: Write the Readings|p.336; I-A & B',
  'lesson-22/literacy-10|Reading Practice: 桜さんの日記|p.337-339; II-B, C, & D',
  'lesson-22/literacy-wb-1|Workbook: Kanji Writing Practice|p.129',
  'lesson-22/literacy-wb-2|Workbook: Using Kanji|p.130',
  
  // Lesson 23
  'lesson-23/vocab-1|Vocabulary: Nouns 1|p.252',
  'lesson-23/vocab-2|Vocabulary: Nouns 2|p.252',
  'lesson-23/vocab-3|Vocabulary: Adjectives and U-verbs|p.252-253',
  'lesson-23/vocab-4|Vocabulary: Ru-verbs and Irregular Verbs|p.253',
  'lesson-23/vocab-5|Vocabulary: Adverbs and Other Expressions|p.253',
  'lesson-23/grammar-1|Practice: Causative-passive Sentences 1|p.260; I-A',
  'lesson-23/grammar-2|Practice: Causative-passive Sentences 2|p.260-261; I-B',
  'lesson-23/grammar-3|Practice: Causative-passive Sentences 3|p.261; I-C',
  'lesson-23/grammar-4|Practice: ～ても 1|p.262-263; II-A',
  'lesson-23/grammar-5|Practice: ～ても 2|p.263; II-B',
  'lesson-23/grammar-6|Practice: ～ことにする|p.264; III-A',
  'lesson-23/grammar-7|Practice: ～ことにしている|p.265; IV-A',
  'lesson-23/grammar-8|Practice: ～まで|p.266; V-A',
  'lesson-23/grammar-9|Practice: ～方|p.268; VI-A',
  'lesson-23/culture-1|Culture Note: Japanese Proverbs|p.272',
  'lesson-23/workbook-1|Workbook: Causative-passive Sentences 1|p.97-98; I & II',
  'lesson-23/workbook-2|Workbook: Causative-passive Sentences 2|p.99; I & II',
  'lesson-23/workbook-3|Workbook: Passive and Causative-passive|p.100',
  'lesson-23/workbook-4|Workbook: ～ても|p.101; I & II',
  'lesson-23/workbook-5|Workbook: ～ことにする|p.102; I & II',
  'lesson-23/workbook-6|Workbook: ～ことにしている|p.103; I & II',
  'lesson-23/workbook-7|Workbook: ～まで|p.104; I & II',
  'lesson-23/workbook-8|Workbook: ～方|p.105; I & II',
  'lesson-23/workbook-9|Workbook: Questions|p.106; I',
  'lesson-23/workbook-10|Workbook: Listening Comprehension|p.107; A, B, & C',
  'lesson-23/literacy-1|Kanji Practice: Readings|p.340-341',
  'lesson-23/literacy-2|Kanji Practice: Meanings|p.340-341',
  'lesson-23/literacy-3|Kanji Practice: Stroke Order|p.340-341',
  'lesson-23/literacy-4|Kanji Vocabulary: 顔, 悲, and 怒|p.340',
  'lesson-23/literacy-5|Kanji Vocabulary: 違, 変, and 比|p.340',
  'lesson-23/literacy-6|Kanji Vocabulary: 情, 感, and 調|p.340-341',
  'lesson-23/literacy-7|Kanji Vocabulary: 査, 果, and 化|p.341',
  'lesson-23/literacy-8|Kanji Vocabulary: 横, 相, and 答|p.341',
  'lesson-23/literacy-9|Kanji Practice: Write the Readings|p.342; I-A & B',
  'lesson-23/literacy-10|Reading Practice: 顔文字と絵文字|p.343-345; II-A, B, & C',
  'lesson-23/literacy-wb-1|Workbook: Kanji Writing Practice|p.131',
  'lesson-23/literacy-wb-2|Workbook: Using Kanji|p.132',
  
  // Appendix
  'appendix/dictionary|Vocabulary Index (Dictionary)|p.352-383',
  'appendix/grammar-index|Grammar Index',
  'appendix/map-of-japan|Map of Japan|p.384-385',
  'appendix/numbers-chart|Numbers Chart|p.386-387',
  'appendix/conjugation-chart|Conjugation Chart|p.388-389',

  // Study Tools
  'study-tools/custom-vocab|Custom Vocabulary Practice',
  'study-tools/custom-spelling|Custom Spelling Practice',
  'study-tools/custom-quiz|Custom Quiz',
  'study-tools/custom-written-quiz|Custom Written Quiz'
];
