# This file is for GitHub's sponsor button.
# If you like my work and want to say more than thanks, feel free to buy me a coffee, a gift, or send a tip!
github: SethClydesdale
ko_fi: sethc95
custom: ['https://sethclydesdale.github.io/genki-study-resources/donate/']