// Dictionary for Genki Volumes I & II

// # DEFINITION SYNTAX #
// preferred if definitions are kept to one line
/*{
   ja : 'JAPANESE_DEFINITION|FURIGANA(OPTIONAL)', // | should be omitted if no furigana
   en : 'ENGLISH_DEFINITION',
    v : 'VERB_TYPE(OPTIONAL)', // can be omitted if no verb type
    l : 'LESSON'
}*/

// # EMPTY DEFINITION #
// empty definition used when filling in definitions en masse
// { ja : '|', en : '', v : '', l : '会L読L-II' },
// OR: (since there's usually more nouns/adjs than verbs, and doesn't take long to write v : '',)
// { ja : '|', en : '', l : '会L読L-II' },

Genki.jisho = {
  
  'あ' : [
    { ja : '相変わらず|あいかわらず', en : 'as usual', l : '読L22-II' },
    { ja : '愛す|あいす', en : 'to love', v : 'u', l : '読L14-II' },
    { ja : 'アイスクリーム', en : 'ice cream', l : '会L3' },
    { ja : '間|あいだ', en : 'between', l : '会L4' },
    { ja : '～間に|～あいだに', en : 'while...', l : '会L21' },
    { ja : '相手|あいて', en : 'partner', l : '会L22' },
    { ja : 'アイロンをかける', en : 'to iron (clothes)', v : 'ru', l : '会L16' },
    { ja : '会う|あう', en : 'to meet; to see (a person)', v : 'u', l : '会L4' },
    { ja : 'アウトドア', en : 'outdoor activities', l : '読L11-II' },
    { ja : '青い|あおい', en : 'blue', l : '会L9, 会L9(e)' },
    { ja : '赤い|あかい', en : 'red', l : '会L9, 会L9(e)' },
    { ja : '赤ちゃん|あかちゃん', en : 'baby', l : '会L21' },
    { ja : '明るい|あかるい', en : 'bright; cheerful', l : '会L18, 読L11-II' },
    { ja : '秋|あき', en : 'fall', l : '会L10' },
    { ja : 'あきらめる', en : 'to give up', v : 'ru', l : '会L14' },
    { ja : '開く|あく', en : '(something) opens', v : 'u', l : '会L18' },
    { ja : '開ける|あける', en : 'to open (something)', v : 'ru', l : '会L6' },
    { ja : 'あげる', en : 'to give (to others)', v : 'ru', l : '会L14' },
    { ja : '朝|あさ', en : 'morning', l : '会L3' },
    { ja : '朝ご飯|あさごはん', en : 'breakfast', l : '会L3' },
    { ja : 'あさって', en : 'the day after tomorrow', l : '会L4(e), 会L8' },
    { ja : '朝寝坊する|あさねぼうする', en : 'to oversleep', v : 'irr', l : '会L16' },
    { ja : '足|あし', en : 'leg; foot', l : '会L7(e), 会L12' },
    { ja : 'アジア研究|アジアけんきゅう', en : 'Asian studies', l : '会L1' },
    { ja : '明日|あした', en : 'tomorrow', l : '会L3, 会L4(e)' },
    { ja : 'あそこ', en : 'over there', l : '会L2' },
    { ja : '遊ぶ|あそぶ', en : 'to play; to spend time pleasantly', v : 'u', l : '会L6' },
    { ja : '暖かい|あたたかい', en : 'warm', l : '会L10' },
    { ja : '頭|あたま', en : 'head', l : '会L7(e)' },
    { ja : '頭がいい|あたまがいい', en : 'bright; smart; clever', l : '会L7' },
    { ja : '新しい|あたらしい', en : 'new', l : '会L5' },
    { ja : 'あちら', en : 'that way (place)', l : '会L20' },
    { ja : '熱い|あつい', en : 'hot (thing)', l : '会L5' },
    { ja : '暑い|あつい', en : 'hot (weather)', l : '会L5' },
    { ja : '集める|あつめる', en : 'to collect', v : 'ru', l : '会L16' },
    { ja : '後|あと', en : 'the rest', l : '会L18' },
    { ja : '後|あと', en : 'after (an event)', l : '読L8-II, 会L11' },
    { ja : '後で|あとで', en : 'later on', l : '会L6' },
    { ja : 'アドバイス', en : 'advice', l : '読L14-II' },
    { ja : 'あなた', en : 'you', l : '会L4' },
    { ja : '兄|あに', en : '(my) older brother', l : '会L14' },
    { ja : 'アニメ', en : 'animation', l : '会L20' },
    { ja : '姉|あね', en : '(my) older sister', l : '会L7' },
    { ja : 'あの', en : 'that...(over there); um...', l : '会L1, 会L2' },
    { ja : 'アパート', en : 'apartment', l : '会L7' },
    { ja : '危ない|あぶない', en : 'dangerous', l : '会L17' },
    { ja : '甘い|あまい', en : 'sweet', l : '会L12' },
    { ja : '天の川|あまのがわ', en : 'the Milky Way', l : '読L12-II' },
    { ja : 'あまり', en : 'not much (with neg. sentence)', l : '会L3' },
    { ja : '編む|あむ', en : 'to knit', v : 'u', l : '会L13' },
    { ja : '雨|あめ', en : 'rain', l : '会L8' },
    { ja : '雨が降る|あめがふる', en : 'it rains', v : 'u', l : '会L8' },
    { ja : '雨がやむ|あめがやむ', en : 'the rain stops', v : 'u', l : '会L23' },
    { ja : 'アメリカ', en : 'U.S.A.', l : '会L1, 会L2' },
    { ja : '謝る|あやまる', en : 'to apologize', v : 'u', l : '会L18' },
    { ja : '洗う|あらう', en : 'to wash', v : 'u', l : '会L8' },
    { ja : '表す|あらわす', en : 'to express; to show', v : 'u', l : '読L23-II' },
    { ja : 'ありがとう', en : 'Thank you.', l : '会G' },
    { ja : 'ありがとうございます', en : 'Thank you. (polite)', l : '会G' },
    { ja : 'ある', en : 'there is...', v : 'u', l : '会L4' },
    { ja : 'ある～', en : 'one...', l : '読L12-II' },
    { ja : '歩いて|あるいて', en : 'on foot', l : '会L10' },
    { ja : '歩く|あるく', en : 'to walk', v : 'u', l : '会L12' },
    { ja : 'アルバイト', en : 'part-time job', l : '会L4' },
    { ja : 'あれ', en : 'that one (over there)', l : '会L2' },
    { ja : 'アンケート', en : 'questionnaire', l : '読L8-II' },
    { ja : '暗証番号|あんしょうばんごう', en : 'personal identificiation number', l : '会L13(e)' },
    { ja : '安全|あんぜん（な）', en : 'safe', l : '会L21' },
    { ja : '案内する|あんないする', en : 'to show (someone) around', v : 'irr', l : '読L9-II, 会L16' },
    { ja : 'あんなに', en : 'so; such', l : '読L20-II' }
  ],
  
  'い' : [
    { ja : 'いい', en : 'good', l : '会L3' },
    { ja : 'いいえ', en : 'No.; Not at all.', l : '会G' },
    { ja : 'いい子|いいこ', en : 'good child', l : '会L9' },
    { ja : 'いいこと', en : 'good deed', l : '読L10-II' },
    { ja : '言う|いう', en : 'to say', v : 'u', l : '会L8' },
    { ja : '家|いえ', en : 'house; home', l : '会L3' },
    { ja : '～以外|～いがい', en : 'other than...', l : '読L16-II' },
    { ja : 'いかが', en : 'how (polite exp. of どう)', l : '読L19-II' },
    { ja : '～行き|～いき', en : 'bound for...', l : '会L10(e)' },
    { ja : 'イギリス', en : 'Britain', l : '会L1, 会L2' },
    { ja : '行く|いく', en : 'to go', v : 'u', l : '会L3' },
    { ja : 'いくら', en : 'how much', l : '会L2' },
    { ja : 'いじめる', en : 'to bully', v : 'ru', l : '会L21' },
    { ja : '医者|いしゃ', en : 'doctor', l : '会L1, 会L10' },
    { ja : '～以上|～いじょう', en : '...or more', l : '読L18-II' },
    { ja : '意地悪|いじわる（な）', en : 'mean-spirited', l : '会L9' },
    { ja : 'いす', en : 'chair', l : '会L2(e), 会L4' },
    { ja : '忙しい|いそがしい', en : 'busy (people/days)', l : '会L5' },
    { ja : '急ぐ|いそぐ', en : 'to hurry', v : 'u', l : '会L6' },
    { ja : '痛い|いたい', en : 'hurt; painful', l : '会L12' },
    { ja : '致す|いたす', en : 'extra-modest exp. for する', v : 'u', l : '会L20' },
    { ja : 'いただきます', en : 'Thank you for the meal. (before eating)', l : '会G' },
    { ja : '頂く|いただく', en : 'extra-modest exp. for たべる and のむ; humble exp. for もらう', v : 'u', l : '会L20' },
    { ja : 'イタリア', en : 'Italy', l : '読L6-III' },
    { ja : '一月|いちがつ', en : 'January', l : '会L4(e)' },
    { ja : '一号車|いちごうしゃ', en : 'Car No. 1', l : '会L19(e)' },
    { ja : '一時|いちじ', en : "one o'clock", l : '会L1, 会L1(e)' },
    { ja : '一時間|いちじかん', en : 'one hour', l : '会L4' },
    { ja : '一日|いちにち', en : 'one day', l : '会L13' },
    { ja : '一日中|いちにちじゅう', en : 'all day long', l : '会L15' },
    { ja : '一年中|いちねんじゅう', en : 'all year', l : '読L15-II' },
    { ja : '一年生|いちねんせい', en : 'first-year student', l : '会L1' },
    { ja : '一年に一度|いちねんにいちど', en : 'once a year', l : '読L12-II' },
    { ja : '一番|いちばん', en : 'best', l : '会L10' },
    { ja : '一番後ろ|いちばんうしろ', en : 'last car; tail end', l : '会L10(e)' },
    { ja : '一番前|いちばんまえ', en : 'first car; front end', l : '会L10(e)' },
    { ja : 'いつ', en : 'when', l : '会L3' },
    { ja : '五日|いつか', en : 'the fifth day of a month; five days', l : '会L4(e), 会L13' },
    { ja : '一歳|いっさい', en : 'one year old', l : '会L1(e)' },
    { ja : '一生懸命|いっしょうけんめい', en : 'very hard', l : '読L21-II' },
    { ja : '一生に一度|いっしょうにいちど', en : 'once in a lifetime', l : '読L13-II' },
    { ja : '一緒に|いっしょに', en : 'together', l : '会L5' },
    { ja : '五つ|いつつ', en : 'five', l : '会L9' },
    { ja : 'いってきます', en : "I'll go and come back.", l : '会G' },
    { ja : 'いってらっしゃい', en : 'Please go and come back.', l : '会G' },
    { ja : '一泊二食付|いっぱくにしょくつき', en : 'one night with two meals', l : '会L15(e)' },
    { ja : '一分|いっぷん', en : 'one minute', l : '会L1(e)' },
    { ja : 'いつも', en : 'always', l : '読L6-III, 会L8' },
    { ja : 'いなか', en : 'countryside', l : '読L20-II' },
    { ja : 'いなくなる', en : 'to disappear; (someone) is gone', v : 'u', l : '会L23' },
    { ja : '犬|いぬ', en : 'dog', l : '会L4' },
    { ja : '今|いま', en : 'now', l : '会L1' },
    { ja : '今すぐ|いますぐ', en : 'right away', l : '会L18' },
    { ja : '意味|いみ', en : 'meaning', l : '会L11(e), 会L12' },
    { ja : '妹|いもうと', en : 'younger sister', l : '会L1, 会L7' },
    { ja : 'いや', en : 'no', l : '会L23' },
    { ja : 'いらっしゃいます', en : '(someone honorable) is present/home', l : '会L13' },
    { ja : 'いらっしゃいませ', en : 'Welcome (to our store).', l : '会L2' },
    { ja : 'いらっしゃる', en : 'honorific exp. for いく, くる, and いる', v : 'u', l : '会L19' },
    { ja : '入口|いりぐち', en : 'entrance', l : '会L10(e)' },
    { ja : 'いる', en : '(a person) is in...; stays at...', v : 'ru', l : '会L4' },
    { ja : '要る|いる', en : 'to need', v : 'u', l : '会L8' },
    { ja : 'いれる', en : 'to make tea, coffee, etc.', v : 'ru', l : '会L17' },
    { ja : '入れる|いれる', en : 'to put (something) in', v : 'ru', l : '会L16' },
    { ja : '色|いろ', en : 'color', l : '会L9' },
    { ja : 'いろいろ（な）', en : 'various; different kinds of', l : '読L9-II, 会L13' },
    { ja : 'インターネット', en : 'Internet', l : '会L15' }
  ],
  
  'う' : [
    { ja : 'ううん', en : 'uh-uh; no', l : '会L8' },
    { ja : '上|うえ', en : 'above; on', l : '会L4' },
    { ja : 'ウエイター', en : 'waiter', l : '会L13' },
    { ja : '伺う|うかがう', en : 'to humbly visit; to humbly ask', v : 'u', l : '会L20' },
    { ja : '受付|うけつけ', en : 'reception desk', l : '会L22' },
    { ja : '受ける|うける', en : 'to take (an examination, interview, etc.)', v : 'ru', l : '読L19-III, 会L23' },
    { ja : '牛|うし', en : 'cow', l : '読L12-II' },
    { ja : '後ろ|うしろ', en : 'back', l : '会L4' },
    { ja : 'うそをつく', en : 'to tell a lie', v : 'u', l : '会L11' },
    { ja : '歌|うた', en : 'song', l : '会L7' },
    { ja : '歌う|うたう', en : 'to sing', v : 'u', l : '会L7' },
    { ja : 'うち', en : 'home; house; my place', l : '会L3' },
    { ja : '宇宙人|うちゅうじん', en : 'space alien', l : '会L20' },
    { ja : '宇宙飛行士|うちゅうひこうし', en : 'astronaut', l : '会L11' },
    { ja : '写す|うつす', en : 'to copy', v : 'u', l : '読L16-II' },
    { ja : 'うまく', en : 'well; successfully; skillfully', l : '読L22-II' },
    { ja : 'うまくいく', en : 'to go well', v : 'u', l : '読L22-II' },
    { ja : '生まれる|うまれる', en : 'to be born', v : 'ru', l : '読L15-II, 会L17' },
    { ja : '海|うみ', en : 'sea', l : '会L5' },
    { ja : '占い|うらない', en : 'fortunetelling', l : '読L21-II' },
    { ja : 'うちやましい', en : 'envious', l : '会L17' },
    { ja : 'うちやましがる', en : '(somebody is) envious', l : '読L22-II' },
    { ja : '売る|うる', en : 'to sell', v : 'u', l : '読L10-II, 会L15' },
    { ja : 'うるさい', en : 'noisy; annoying', l : '会L22' },
    { ja : 'うれしい', en : 'glad', l : '会L13' },
    { ja : '売れる|うれる', en : 'to be sold', v : 'ru', l : '読L20II' },
    { ja : 'うん', en : 'uh-huh; yes', l : '会L8' },
    { ja : '運転する|うんてんする', en : 'to drive', v : 'irr', l : '会L8' },
    { ja : '運動する|うんどうする', en : 'to do physical exercises', v : 'irr', l : '会L9' }
  ],
  
  'え' : [
    { ja : '絵|え', en : 'painting; picture; drawing', l : '会L15' },
    { ja : 'エアコン', en : 'air conditioner', l : '会L18' },
    { ja : '映画|えいが', en : 'movie', l : '会L3' },
    { ja : '英会話|えいかいわ', en : 'English conversation', l : '会L22' },
    { ja : '映画館|えいがかん', en : 'movie theater', l : '会L15' },
    { ja : '影響を受ける|えいきょうをうける', en : 'to be affected', v : 'ru', l : '読L17-II' },
    { ja : '英語|えいご', en : 'English language', l : '会L1' },
    { ja : 'ええ', en : 'yes', l : '会L1' },
    { ja : 'ええと', en : 'well...; let me see...', l : '会L16' },
    { ja : '駅|えき', en : 'station', l : '読L6-I, 会L10' },
    { ja : '駅員|えきいん', en : 'station attendant', l : '会L16' },
    { ja : 'えさ', en : 'feed', l : '読L20-II' },
    { ja : '江戸|えど', en : 'former name of Tokyo', l : '読L20-II' },
    { ja : '江戸時代|えどじだい', en : 'Edo period', l : '読L20-II' },
    { ja : '選ぶ|えらぶ', en : 'to choose; to select', v : 'u', l : '会L17' },
    { ja : 'えん|円', en : 'yen', l : '会L2' },
    { ja : '鉛筆|えんぴつ', en : 'pencil', l : '会L2, 会L2(e)' },
    { ja : '遠慮する|えんりょする', en : 'to hold back for the time being; to refrain from', v : 'irr', l : '会L19' }
  ],
  
  'お' : [
    { ja : 'お預入れ|おあずけいれ', en : 'deposit', l : '会L13(e)' },
    { ja : 'おいしい', en : 'delicious', l : '会L2' },
    { ja : 'お祈りする|おいのりする', en : 'to pray', v : 'irr', l : '会L17' },
    { ja : '往復|おうふく', en : 'round trip', l : '会L10(e)' },
    { ja : '多い|おおい', en : 'there are many...', l : '会L12' },
    { ja : '大きい|おおきい', en : 'large', l : '会L5' },
    { ja : '大きさ|おおきさ', en : 'size', l : '会L16' },
    { ja : '多くの～|おおくの～', en : 'many...', l : '読L21-II' },
    { ja : 'オーストラリア', en : 'Australia', l : '会L1, 会L11' },
    { ja : '大家さん|おおやさん', en : 'landlord; landlady', l : '会L14' },
    { ja : 'お母さん|おかあさん', en : 'mother', l : '会L1, 会L2' },
    { ja : 'お返し|おかえし', en : 'return (as a token of gratitude)', l : '会L14' },
    { ja : 'おかえり（なさい）', en : 'Welcome home.', l : '会G' },
    { ja : 'おかげで', en : 'thanks to...', l : '会L18' },
    { ja : 'お菓子|おかし', en : 'snack; sweets', l : '会L11' },
    { ja : 'お金|おかね', en : 'money', l : '会L6' },
    { ja : 'お金持ち|おかねもち', en : 'rich person', l : '会L10' },
    { ja : 'お客さん|おきゃくさん', en : 'guest; visitor; client; customer', l : '会L17' },
    { ja : '起きる|おきる', en : 'to get up', v : 'ru', l : '会L3' },
    { ja : '置く|おく', en : 'to put; to lay; to place', v : 'u', l : '会L21' },
    { ja : '奥様|おくさま', en : '(your/his) wife (polite)', l : '会L19' },
    { ja : '奥さん|おくさん', en : '(your/his) wife', l : '会L14' },
    { ja : '送る|おくる', en : 'to send; to walk/drive (someone)', v : 'u', l : '会L14, 会L19' },
    { ja : '遅れる|おくれる', en : 'to become late', v : 'ru', l : '会L19' },
    { ja : 'お子さん|おこさん', en : '(you/their) child (polite)', l : '会L19' },
    { ja : '起こす|おこす', en : 'to wake (someone) up', v : 'u', l : '会L16' },
    { ja : '怒る|おこる', en : 'to get angry', v : 'u', l : '読L12-II, 会L19' },
    { ja : '起こる|おこる', en : 'to occur; to happen', v : 'u', l : '読L21-II' },
    { ja : 'おごる', en : 'to treat (someone) to a meal', v : 'u', l : '会L16' },
    { ja : 'お先に失礼します|おさきにしつれいします', en : "See you. (lit. I'm leaving ahead of you.)", l : '会L18' },
    { ja : 'お酒|おさけ', en : 'sake; alcohol', l : '会L3' },
    { ja : 'おじいさん', en : 'grandfather; old man', l : '会L7' },
    { ja : '教える|おしえる', en : 'to teach; to instruct', v : 'ru', l : '会L6' },
    { ja : 'おじさん', en : 'uncle; middle-aged man', l : '会L14' },
    { ja : 'おじぞうさん', en : 'guardian deity of children', l : '読L10-II' },
    { ja : 'お正月|おしょうがつ', en : "New Year's", l : '読L10-II, 会L11' },
    { ja : 'お嬢さん|おじょうさん', en : "(someone's daughter) polite", l : '会L22' },
    { ja : 'おしり', en : 'buttocks', l : '会L7(e)' },
    { ja : 'お城|おしろ', en : 'castle', l : '読L5-II' },
    { ja : '押す|おす', en : 'to press; to push', v : 'u', l : '会L18' },
    { ja : 'お世話になる|おせわになる', en : "to be in someone's care", v : 'u', l : '読L19-II, 会L23' },
    { ja : '遅い|おそい', en : 'slow; late', l : '会L10' },
    { ja : '遅く|おそく', en : '(do something) late', l : '読L4-III, 会L6' },
    { ja : '遅くなる|おそくなる', en : 'to be late', v : 'u', l : '会L8' },
    { ja : 'お大事に|おだいじに', en : 'Get well soon.', l : '会L12' },
    { ja : 'お宅|おたく', en : "(someone's) house/home", l : '会L13' },
    { ja : '落ち込む|おちこむ', en : 'to get depressed', v : 'u', l : '会L16' },
    { ja : 'お茶|おちゃ', en : 'green tea', l : '会L3' },
    { ja : '落ちる|おちる', en : '(something) drops', v : 'ru', l : '会L18' },
    { ja : 'おつかれさま（でした）|お疲れ様（でした）', en : 'You must be tired after working so hard. (ritualistic exp.)', l : '会L18' },
    { ja : 'おっしゃる', en : 'honorific exp. for いう', v : 'u', l : '会L19' },
    { ja : 'お手洗い|おてあらい', en : 'restroom', l : '会L12' },
    { ja : 'お寺|おてら', en : 'temple', l : '会L4' },
    { ja : '音|おと', en : 'sound', l : '会L20' },
    { ja : 'お父さん|おとうさん', en : 'father', l : '会L1, 会L2' },
    { ja : '弟|おとうと', en : 'younger brother', l : '会L1, 会L17' },
    { ja : '男|おとこ', en : 'man', l : '読L11-II, 会L17' },
    { ja : '男の子|おとこのこ', en : 'boy', l : '会L11' },
    { ja : '男の人|おとこのひと', en : 'man', l : '会L7' },
    { ja : '落とされる|おとされる', en : 'to be dropped', l : '読L15-II' },
    { ja : '落とす|おとす', en : 'to drop (something)', v : 'u', l : '会L18' },
    { ja : 'おととい', en : 'the day before yesterday', l : '会L4(e), 会L19' },
    { ja : 'おととし', en : 'the year before last', l : '会L4(e)' },
    { ja : '大人|おとな', en : 'adult', l : '読L12-II, 会L13' },
    { ja : '踊る|おどる', en : 'to dance', v : 'u', l : '会L9' },
    { ja : 'おなか', en : 'stomach', l : '会L7(e), 会L12' },
    { ja : 'おなかがすく', en : 'to become hungry', v : 'u', l : '会L11' },
    { ja : 'おなかをこわす', en : 'to have a stomachache', v : 'u', l : '会L23' },
    { ja : '同じ|おなじ', en : 'same', l : '読L13-III, 会L14' },
    { ja : '同じような|おなじような', en : 'similar', l : '読L23-II' },
    { ja : 'お兄さん|おにいさん', en : 'older brother', l : '会L1, 会L7' },
    { ja : 'おにぎり', en : 'rice ball', l : '会L20' },
    { ja : 'お姉さん|おねえさん', en : 'older sister', l : '会L1, 会L7' },
    { ja : 'おねがいします', en : '...,please.', l : '会L2' },
    { ja : 'お願いする|おねがいする', en : 'to pray for help', v : 'irr', l : '会L22' },
    { ja : 'おばあさん', en : 'grandmother; old woman', l : '会L7' },
    { ja : 'おばさん', en : 'aunt; middle-aged woman', l : '会L14' },
    { ja : 'おはよう', en : 'Good morning.', l : '会G' },
    { ja : 'おはようございます', en : 'Good morning. (polite)', l : '会G' },
    { ja : 'お引き出し|おひきだし', en : 'withdrawal', l : '会L13(e)' },
    { ja : 'お振込|おふりこみ', en : 'bank transfer', l : '会L13(e)' },
    { ja : 'お風呂|おふろ', en : 'bath', l : '会L6' },
    { ja : 'お風呂に入る|おふろにはいる', en : 'to take a bath', v : 'u', l : '会L6' },
    { ja : 'お返事|おへんじ', en : 'reply', l : '読L11-II' },
    { ja : 'お弁当|おべんとう', en : 'boxed lunch', l : '会L9' },
    { ja : '覚える|おぼえる', en : 'to memorize', v : 'ru', l : '会L9' },
    { ja : 'お祭り|おまつり', en : 'festival', l : '会L11' },
    { ja : 'お守り|おまもり', en : 'charm (against evils); amulet', l : '読L21-II' },
    { ja : 'おまんじゅう', en : 'sweet bun', l : '読L4-III' },
    { ja : 'お土産|おみやげ', en : 'souvenir', l : '会L4' },
    { ja : 'おめでとうございます', en : 'Congratulations!', l : '会L17' },
    { ja : '重い|おもい', en : 'heavy; serious (illness)', l : '会L20' },
    { ja : '思い出す|おもいだす', en : 'to recall', v : 'u', l : '読L19-II' },
    { ja : '思い出|おもいで', en : 'memory', l : '会L23' },
    { ja : '思う|おもう', en : 'to think', v : 'u', l : '会L8' },
    { ja : '面白い|おもしろい', en : 'interesting; funny', l : '会L5' },
    { ja : 'おもち', en : 'rice cake', l : '読L10-II' },
    { ja : 'おもちゃ', en : 'toy', l : '会L11' },
    { ja : '主に|おもに', en : 'mainly', l : '読L17-II' },
    { ja : '親|おや', en : 'parent', l : '会L16' },
    { ja : 'おや?', en : 'Oh!', l : '会L20' },
    { ja : 'おやすみ（なさい）', en : 'Good night.', l : '会G' },
    { ja : 'お休みになる|おやすみになる', en : 'honorific exp. for ねる', v : 'u', l : '会L19' },
    { ja : 'お湯|おゆ', en : 'hot water', l : '会L17' },
    { ja : 'お湯が沸く|おゆがわく', en : 'water boils', v : 'u', l : '会L18' },
    { ja : 'お湯を沸かす|おゆをわかす', en : 'to boil water', v : 'u', l : '会L17' },
    { ja : '泳ぐ|およぐ', en : 'to swim', v : 'u', l : '会L5' },
    { ja : '降りる|おりる', en : 'to get off', v : 'ru', l : '会L6' },
    { ja : 'おる', en : 'extra-modest exp. for いる', v : 'u', l : '会L20' },
    { ja : 'お礼|おれい', en : 'exp. of gratitude', l : '会L19' },
    { ja : '下ろす|おろす', en : 'to withdraw (money)', v : 'u', l : '会L15' },
    { ja : '終わる|おわる', en : '(something) ends', v : 'u', l : '会L9' },
    { ja : '音楽|おんがく', en : 'music', l : '会L3' },
    { ja : '温泉|おんせん', en : 'spa; hot spring', l : '会L11' },
    { ja : '女|おんな', en : 'woman', l : '読L11-II, 会L17' },
    { ja : '女の子|おんなのこ', en : 'girl', l : '会L11' },
    { ja : '女の人|おんなのひと', en : 'woman', l : '会L7' }
  ],
  
  'か' : [
    { ja : '蚊|か', en : 'mosquito', l : '会L21' },
    { ja : '～か～', en : 'or', l : '会L10' },
    { ja : '～が', en : '...,but', l : '読L5-II, 会L7' },
    { ja : 'カーテン', en : 'curtain', l : '会L2(e), 会L18' },
    { ja : '～階|～かい', en : '...th floor', l : '会L20' },
    { ja : '～回|～かい', en : '...times', l : '会L13' },
    { ja : '海外旅行|かいがいりょこう', en : 'trip to a foreign country', l : '会L23' },
    { ja : '会議|かいぎ', en : 'business meeting; conference', l : '会L21' },
    { ja : '外国|がいこく', en : 'foreign country', l : '会L11' },
    { ja : '外国語|がいこくご', en : 'foregin language', l : '会L13' },
    { ja : '外国人|がいこくじん', en : 'foreigner', l : '会L15' },
    { ja : '改札|かいさつ', en : 'gate', l : '会L10(e)' },
    { ja : '会社|かいしゃ', en : 'company', l : '会L7' },
    { ja : '会社員|かいしゃいん', en : 'office worker', l : '会L1, 会L8' },
    { ja : '回数券|かいすうけん', en : 'coupons', l : '会L10(e)' },
    { ja : '階段|かいだん', en : 'stairs', l : '会L10(e)' },
    { ja : '買い物|かいもの', en : 'shopping', l : '会L4' },
    { ja : '買う|かう', en : 'to buy', v : 'u', l : '会L4' },
    { ja : '飼う|かう', en : 'to own (a pet)', v : 'u', l : '会L11' },
    { ja : '返す|かえす', en : 'to return (a thing)', v : 'u', l : '会L6' },
    { ja : '帰ってくる|かえってくる', en : 'to come back home', v : 'irr', l : '読L22-II' },
    { ja : '換える|かえる', en : 'to change', v : 'ru', l : '会L23' },
    { ja : '帰る|かえる', en : 'to go back; to return', v : 'u', l : '会L3' },
    { ja : '顔|かお', en : 'face', l : '会L7(e), 会L10' },
    { ja : '顔が青い|かおがあおい', en : 'to look pale', l : '会L9(e)' },
    { ja : '～顔をする|～かおをする', en : 'to look...(facial exp.)', v : 'irr', l : '会L23' },
    { ja : '科学|かがく', en : 'science', l : '会L1' },
    { ja : '係の者|かかりのもの', en : 'our person in charge', l : '会L20' },
    { ja : 'かかる', en : 'to take (ammount of time/money)', v : 'u', l : '会L10' },
    { ja : 'かぎ', en : 'lock; key', l : '会L17' },
    { ja : '書留|かきとめ', en : 'registered mail', l : '会L5(e)' },
    { ja : 'かぎをかける', en : 'to lock', v : 'ru', l : '会L17' },
    { ja : '描く|かく', en : 'to draw; to paint', v : 'u', l : '会L15' },
    { ja : '書く|かく', en : 'to write', v : 'u', l : '会L4' },
    { ja : '家具|かぐ', en : 'furniture', l : '会L15' },
    { ja : '学生|がくせい', en : 'student', l : '会L1' },
    { ja : '学割|がくわり', en : 'student discount', l : '会L10(e)' },
    { ja : '～か月|～かげつ', en : 'for...months', l : '会L10' },
    { ja : 'かける', en : 'to sit down', v : 'ru', l : '会L19' },
    { ja : 'かける（めがねを）', en : 'to put on (glasses)', v : 'ru', l : '会L7' },
    { ja : 'かさ', en : 'bamboo hat', l : '読L10-II' },
    { ja : '傘|かさ', en : 'umbrella', l : '会L2' },
    { ja : '菓子|かし', en : 'snacks; sweets', l : '会L11' },
    { ja : '火事|かじ', en : 'fire', l : '会L17' },
    { ja : '家事|かじ', en : 'household matters', l : '会L22' },
    { ja : 'かしこまりました', en : 'Certainly.', l : '会L20' },
    { ja : '歌手|かしゅ', en : 'singer', l : '会L11' },
    { ja : '貸す|かす', en : 'to lend; to rent', v : 'u', l : '会L13' },
    { ja : '風邪|かぜ', en : 'cold', l : '会L12' },
    { ja : '風|かぜ', en : 'wind', l : '会L22' },
    { ja : '風が吹く|かぜがふく', en : 'the wind blows', v : 'u', l : '会L22' },
    { ja : '風邪をひく|かぜをひく', en : 'to catch a cold', v : 'u', l : '会L12' },
    { ja : '数える|かぞえる', en : 'to count', v : 'ru', l : '読L17-II' },
    { ja : '家族|かぞく', en : 'family', l : '会L7' },
    { ja : 'ガソリン', en : 'gasoline', l : '会L21' },
    { ja : '肩|かた', en : 'shoulder', l : '会L7(e)' },
    { ja : 'かたい言い方|かたいいいかた', en : 'bookish exp.', l : '会L11(e)' },
    { ja : '片付ける|かたづける', en : 'to tidy up', v : 'ru', l : '会L18' },
    { ja : '片道|かたみち', en : 'one way', l : '会L10(e)' },
    { ja : '勝つ|かつ', en : 'to win', v : 'u', l : '会L22' },
    { ja : 'がっかりする', en : 'to be disappointed', v : 'irr', l : '読L20-II, 会L23' },
    { ja : '楽器|がっき', en : 'musical instrument', l : '会L13' },
    { ja : 'かっこ', en : 'parenthesis', l : '会L11(e)' },
    { ja : 'かっこいい', en : 'good-looking', l : '会L5' },
    { ja : '学校|がっこう', en : 'school', l : '会L3' },
    { ja : 'カット', en : 'cut', l : '会L17(e)' },
    { ja : '活動|かつどう', en : 'activities', l : '読L17-II' },
    { ja : '家庭教師|かていきょうし', en : 'tutor', l : '読L18-III' },
    { ja : '角|かど', en : 'corner', l : '会L6(e), 会L20' },
    { ja : '～かな（あ）', en : 'I wonder...(casual)', l : '会L17' },
    { ja : 'かなう', en : 'to be realized', v : 'u', l : '読L12-II' },
    { ja : '悲しい|かなしい', en : 'sad', l : '読L10-II, 会L13' },
    { ja : '金|かね', en : 'money', l : '会L6' },
    { ja : '金持ち|かねもち', en : 'rich person', l : '会L10' },
    { ja : '彼女|かのじょ', en : 'girlfriend; she; her', l : '読L11-II, 会L12' },
    { ja : 'かばん', en : 'bag', l : '会L2, 会L2(e)' },
    { ja : '歌舞伎|かぶき', en : 'Kabuki; traditional Japanese theatrical art', l : '会L9' },
    { ja : 'かぶせる', en : "to put (a hat) on a person's head", v : 'ru', l : '読L10-II' },
    { ja : 'かぶる', en : 'to put on (a hat)', v : 'u', l : '会L7' },
    { ja : '我慢する|がまんする', en : 'to be tolerant/patient', v : 'irr', l : '会L23' },
    { ja : '髪|かみ', en : 'hair', l : '会L7, 会L7(e)' },
    { ja : '紙|かみ', en : 'paper', l : '会L17' },
    { ja : '髪形|かみがた', en : 'hair style', l : '会L17(e)' },
    { ja : '神様|かみさま', en : 'God', l : '読L12-II, 会L22' },
    { ja : '髪をとかす|かみをとかす', en : "to comb one's hair", v : 'u', l : '会L17' },
    { ja : 'かめ', en : 'turtle', l : '読L13-II' },
    { ja : 'カメラ', en : 'camera', l : '会L8' },
    { ja : '通う|かよう', en : 'to commute to', v : 'u', l : '読L22-II' },
    { ja : '火曜日|かようび', en : 'Tuesday', l : '会L4, 会L4(e)' },
    { ja : '～から', en : 'because...; from...', l : '会L6, 読L7-II, 会L9' },
    { ja : '辛い|からい', en : 'hot and spicy; salty', l : '会L13' },
    { ja : 'カラオケ', en : 'karaoke', l : '会L8' },
    { ja : '体|からだ', en : 'body', l : '読L13-II, 会L23' },
    { ja : '体にいい|からだにいい', en : 'good for health', l : '読L13-II' },
    { ja : '体に気をつける|からだにきをつける', en : 'to take care of oneself', v : 'ru', l : '読L7-II' },
    { ja : '空手|からて', en : 'karate', l : '会L13' },
    { ja : '借りる|かりる', en : 'to borrow', v : 'u', l : '会L6' },
    { ja : '刈る|かる', en : 'to crop', v : 'u', l : '会L17(e)' },
    { ja : '軽い|かるい', en : 'light', l : '会L20' },
    { ja : '彼|かれ', en : 'boyfriend; he; him', l : '会L12' },
    { ja : 'カレー', en : 'curry', l : '会L13' },
    { ja : '川|かわ', en : 'river', l : '会L11' },
    { ja : 'かわいい', en : 'cute', l : '会L7' },
    { ja : 'かわいそう（な）', en : 'pitiful', l : '読L12-II' },
    { ja : '代わりに|かわりに', en : 'instead', l : '読L22-II' },
    { ja : '眼科|がんか', en : 'ophthalmologist', l : '会L12(e)' },
    { ja : '考える|かんがえる', en : 'to think (about); to consider', v : 'ru', l : '読L13-III, 会L18' },
    { ja : '環境|かんきょう', en : 'environment', l : '会L21' },
    { ja : '観光する|かんこうする', en : 'to do sightseeing', v : 'irr', l : '会L15' },
    { ja : '韓国|かんこく', en : 'Korea', l : '会L1, 会L2' },
    { ja : '看護師|かんごし', en : 'nurse', l : '会L11' },
    { ja : '漢字|かんじ', en : 'kanji; Chinese character', l : '会L6' },
    { ja : '感情|かんじょう', en : 'feeling; emotion', l : '読L23-II' },
    { ja : '完成する|かんせいする', en : 'to be completed', v : 'irr', l : '読L17-II' },
    { ja : '簡単|かんたん（な）', en : 'easy; simple', l : '会L10' },
    { ja : '簡単に|かんたんに', en : 'easily', l : '読L23-II' },
    { ja : '感動する|かんどうする', en : 'to be moved/touched (by...)', v : 'irr', l : '会L13' },
    { ja : '乾杯|かんぱい', en : 'Cheers! (a toast)', l : '会L8' },
    { ja : '頑張る|がんばる', en : "to do one's best; to try hard", v : 'u', l : '会L13' }
  ],
  
  'き' : [
    { ja : '木|き', en : 'tree', l : '会L22' },
    { ja : '黄色い|きいろい', en : 'yellow', l : '会L9(e)' },
    { ja : '消える|きえる', en : '(something) goes off', v : 'ru', l : '会L18' },
    { ja : '気温|きおん', en : 'temperature (weather)', l : '会L12' },
    { ja : '着替える|きがえる', en : 'to change clothes', v :'ru', l : '会L21' },
    { ja : '気が付く|きがつく', en : 'to notice', v : 'u', l : '会L21' },
    { ja : '聞く|きく', en : 'to hear; to listen; to ask', v : 'u', l : '会L3, 会L5' },
    { ja : '聞こえる|きこえる', en : 'to be audible', v : 'ru', l : '会L20' },
    { ja : '季節|きせつ', en : 'season', l : '会L10' },
    { ja : '北|きた', en : 'north', l : '会L6(e)' },
    { ja : 'ギター', en : 'guitar', l : '会L9' },
    { ja : '汚い|きたない', en : 'dirty', l : '会L16' },
    { ja : '喫煙ルーム|きつえんルーム', en : 'smoking room', l : '会L15(e)' },
    { ja : '喫茶店|きっさてん', en : 'cafe', l : '会L12' },
    { ja : '切手|きって', en : 'postal stamps', l : '会L5, 会L5(e)' },
    { ja : '切符|きっぷ', en : 'ticket', l : '会L5' },
    { ja : '切符売り場|きっぷうりば', en : 'ticket vending area', l : '会L10(e)' },
    { ja : '気に入る|きにいる', en : 'to find something agreeable', v : 'u', l : '会L23' },
    { ja : '気にする|きにする', en : 'to worry', v : 'irr', l : '読L21-II' },
    { ja : '昨日|きのう', en : 'yesterday', l : '会L4, 会L4(e)' },
    { ja : '厳しい|きびしい', en : 'strict', l : '会L13' },
    { ja : '気分が悪い|きぶんがわるい', en : 'to feel sick', l : '読L13-II, 会L18' },
    { ja : '期末試験|きまつしけん', en : 'final examination', l : '会L16' },
    { ja : '決まる|きまる', en : 'to be decided', v : 'ru', l : '会L19' },
    { ja : '決める|きまえる', en : 'to decide', v : 'ru', l : '会L10' },
    { ja : '気持ち|きもち', en : 'feeling', l : '読L23-II' },
    { ja : '着物|きもの', en : 'kimono; Japanese tradition dress', l : '読L9-II, 会L13' },
    { ja : 'キャッシュカード', en : 'bank card', l : '会L13(e)' },
    { ja : 'キャンプ', en : 'camp', l : '会L11' },
    { ja : '急行|きゅうこう', en : 'express', l : '会L10(e)' },
    { ja : '九歳|きゅうさい', en : 'nine years old', l : '会L1(e)' },
    { ja : '急に|きゅうに', en : 'suddenly', l : '読L14-II' },
    { ja : '牛乳|ぎゅうにゅう', en : 'milk', l : '会L10' },
    { ja : '九分|きゅうふん', en : 'nine mintues', l : '会L1(e)' },
    { ja : '給料|きゅうりょう', en : 'salary', l : '会L17' },
    { ja : '今日|きょう', en : 'today', l : '会L3, 会L4(e)' },
    { ja : '教科書|きょうかしょ', en : 'textbook', l : '会L6' },
    { ja : '教室|きょうしつ', en : 'classroom', l : '読L16-II' },
    { ja : '今日中に|きょうじゅうに', en : 'by the end of today', l : '会L16' },
    { ja : '兄弟|きょうだい', en : 'brothers and sisters', l : '会L7' },
    { ja : '興味がある|きょうみがある', en : 'to be interested (in)', v : 'u', l : '会L12' },
    { ja : '～行目|～ぎょうめ', en : 'line number...', l : '会L11(e)' },
    { ja : '去年|きょねん', en : 'last year', l : '会L4(e), 会L9' },
    { ja : '嫌い|きらい（な）', en : 'disgusted with; to dislike', l : '会L5' },
    { ja : '切る|きる', en : 'to cut', v : 'u', l : '会L8, 会L17(e)' },
    { ja : '着る|きる', en : 'to put on (clothes above your waist)', v : 'ru', l : '会L7' },
    { ja : 'きれい（な）', en : 'beautiful; clean', l : '会L5' },
    { ja : '～キロ', en : '...kilometers; ...kilograms', l : '会L13' },
    { ja : '気をつける|きをつける', en : 'to be cautious/careful', v : 'ru', l : '会L15' },
    { ja : '金色|きんいろ', en : 'gold', l : '会L9(e)' },
    { ja : '銀色|ぎんいろ', en : 'silver', l : '会L9(e)' },
    { ja : '禁煙車|きんえんしゃ', en : 'nonsmoking car', l : '会L10(e)' },
    { ja : '禁煙ルーム|きんえんルーム', en : 'nonsmoking room', l : '会L15(e)' },
    { ja : '金額|きんがく', en : 'amount', l : '会L13(e)' },
    { ja : '銀行|ぎんこう', en : 'bank', l : '会L2' },
    { ja : '近所|きんじょ', en : 'neighborhood', l : '読L11-II' },
    { ja : '緊張する|きんちょうする', en : 'to get nervous', v : 'irr', l : '会L12' },
    { ja : '金髪|きんぱつ', en : 'blonde hair', l : '会L9(e)' },
    { ja : '金曜日|きんようび', en : 'Friday', l : '会L4, 会L4(e)' }
  ],
  
  'く' : [
    { ja : '空気|くうき', en : 'air', l : '会L8' },
    { ja : '空港|くうこう', en : 'airport', l : '読L13-III, 会L20' },
    { ja : '九月|くがつ', en : 'September', l : '会L4(e)' },
    { ja : '九時|くじ', en : "nine o'clock", l : '会L1(e)' },
    { ja : 'くじら', en : 'whale', l : '読L15-II' },
    { ja : '薬|くすり', en : 'medicine', l : '会L9' },
    { ja : '薬を飲む|くすりをのむ', en : 'to take medicine', v : 'u', l : '会L9' },
    { ja : 'くだけた言い方|くだけたいいかた', en : 'colloguial exp.', l : '会L11(e)' },
    { ja : 'ください', en : 'please give me...', l : '会L2' },
    { ja : '下さる|くださる', en : 'honorific exp. for くれる', v : 'u', l : '会L19' },
    { ja : '口|くち', en : 'mouth', l : '会L7, 会L7(e)' },
    { ja : '靴|くつ', en : 'shoes', l : '会L2' },
    { ja : '靴下|くつした', en : 'socks', l : '会L23' },
    { ja : 'クッション', en : 'cushion', l : '会L18' },
    { ja : '国|くに', en : 'country; place of origin', l : '会L7' },
    { ja : '首|くび', en : 'neck', l : '会L7(e)' },
    { ja : '雲|くも', en : 'cloud', l : '読L17-II' },
    { ja : '曇り|くもり', en : 'cloudy weather', l : '会L12' },
    { ja : '暗い|くらい', en : 'dark', l : '会L18' },
    { ja : '～ぐらい', en : 'amount (approximate measurement)', l : '会L4' },
    { ja : 'クラス', en : 'class', l : '会L4' },
    { ja : 'グラス', en : 'tumbler; glass', l : '会L14' },
    { ja : 'クラブ', en : 'night club', l : '会L15' },
    { ja : '比べる|くらべる', en : 'to compare', v : 'ru', l : '読L23-II' },
    { ja : 'グリーン', en : 'green', l : '会L9(e)' },
    { ja : 'クリスマス', en : 'Christmas', l : '会L14' },
    { ja : '来る|くる', en : 'to come', v : 'irr', l : '会L3' },
    { ja : '車|くるま', en : 'car', l : '会L7' },
    { ja : 'グレー', en : 'gray', l : '会L9(e)' },
    { ja : 'クレジットカード', en : 'credit card', l : '会L10, 会L13(e)' },
    { ja : 'くれる', en : 'to give (me)', v : 'ru', l : '会L14' },
    { ja : '黒い|くろい', en : 'black', l : '会L9, 会L9(e)' },
    { ja : '～君|～くん', en : 'Mr./Ms....(casual)', l : '会L14' }
  ],
  
  'け' : [
    { ja : '計画を立てる|けいかくをたてる', en : 'to make a plan', v : 'ru', l : '会L22' },
    { ja : '経験|けいけん', en : 'experience', l : '読L13-II, 会L15' },
    { ja : '敬語|けいご', en : 'honorific language', l : '会L19' },
    { ja : '経済|けいざい', en : 'economics', l : '会L1, 会L2' },
    { ja : '警察|けいさつ', en : 'police; police station', l : '会L21' },
    { ja : '警察官|けいさつかん', en : 'police officer', l : '会L11' },
    { ja : '芸術|げいじゅつ', en : 'art', l : '読L17-II' },
    { ja : 'ケーキ', en : 'cake', l : '会L10' },
    { ja : 'ゲーム', en : 'game', l : '会L7' },
    { ja : 'けが', en : 'injury', l : '会L12(e)' },
    { ja : '外科|げか', en : 'surgeon', l : '会L12(e)' },
    { ja : '今朝|けさ', en : 'this morning', l : '会L8' },
    { ja : '景色|けしき', en : 'scenery', l : '読L15-II' },
    { ja : '消しゴム|けしゴム', en : 'eraser', l : '会L2(e)' },
    { ja : '化粧する|けしょうする', en : 'to put makeup on', v : 'irr', l : '会L17' },
    { ja : '消す|けす', en : 'to turn off; to erase', v : 'u', l : '会L14' },
    { ja : '結果|けっか', en : 'result', l : '読L23-II' },
    { ja : '結構です|けっこうです', en : "That would be fine.; That wouldn't be necessary.", l : '会L6' },
    { ja : '結婚式|けっこんしき', en : 'wedding', l : '会L15' },
    { ja : '結婚する|けっこんする', en : 'to get married', v : 'irr', l : '会L7' },
    { ja : '月曜日|げつようび', en : 'Monday', l : '会L4, 会L4(e)' },
    { ja : '～けど', en : '...,but; ...,so', l : '会L15' },
    { ja : 'ける', en : 'to kick', v : 'u', l : '会L21' },
    { ja : 'かんかする', en : 'to have a fight; to quarrel', v : 'irr', l : '会L11' },
    { ja : '元気|げんき（な）', en : 'healthy; energetic', l : '会L5' },
    { ja : '元気がない|げんきがない', en : "don't look well", l : '会L12' },
    { ja : '元気でね|げんきでね', en : 'Take care of yourself.', l : '会L23' },
    { ja : '研究|けんきゅう', en : 'research', l : '会L16' },
    { ja : '原爆|げんばく', en : 'atomic bomb', l : '読L15-II' }
  ],
  
  'こ' : [
    { ja : '～個|～こ', en : 'counter for smaller items', l : '会L14, 会L14(e)' },
    { ja : '～後|～ご', en : 'in...time; after...', l : '会L10' },
    { ja : '～語|～ご', en : '...language', l : '会L1' },
    { ja : '公園|こうえん', en : 'park', l : '会L4' },
    { ja : '交換する|こうかんする', en : 'to exchange', v : 'irr', l : '会L20' },
    { ja : '航空便|こうくうびん', en : 'airmail', l : '会L5(e)' },
    { ja : '高校|こうこう', en : 'high school', l : '会L1' },
    { ja : '高校生|こうこうせい', en : 'high school student', l : '会L1' },
    { ja : '広告|こうこく', en : 'advertisement', l : '会L13' },
    { ja : '口座|こうざ', en : 'account', l : '会L13(e)' },
    { ja : '工場|こうじょう', en : 'factory', l : '会L21' },
    { ja : '抗生物質|こうせいぶっしつ', en : 'antibiotic', l : '会L12(e)' },
    { ja : '紅茶|こうちゃ', en : 'tea (black tea)', l : '会L13' },
    { ja : '後輩|こうはい', en : 'junior member of a group', l : '会L22' },
    { ja : '紅葉|こうよう', en : 'red leaves; autumn tints', l : '読L15-II' },
    { ja : '声|こえ', en : 'voice', l : '読L10-II' },
    { ja : 'コーヒー', en : 'coffee', l : '会L3' },
    { ja : 'ゴールド', en : 'gold', l : '会L9(e)' },
    { ja : '五月|ごがつ', en : 'May', l : '会L4(e)' },
    { ja : '国際|こくさい', en : 'international', l : '読L19-III' },
    { ja : '国際関係|こくさいかんけい', en : 'international relations', l : '会L1' },
    { ja : '国際電話|こくさいでんわ', en : 'international call', l : '会L23' },
    { ja : '黒板|こくばん', en : 'blackboard', l : '会L2(e), 会L8' },
    { ja : 'ここ', en : 'here', l : '会L2' },
    { ja : '午後|ごご', en : 'P.M.', l : '会L1' },
    { ja : '九日|ここのか', en : 'the ninth day of a month; nine days', l : '会L4(e), 会L13' },
    { ja : '九つ|ここのつ', en : 'nine', l : '会L9' },
    { ja : '心|こころ', en : 'mind; heart', l : '読L20-II' },
    { ja : '五歳|ごさい', en : 'five years old', l : '会L1(e)' },
    { ja : 'ござる', en : 'extra-modest exp. for ある', v : 'u', l : '会L20' },
    { ja : '五時|ごじ', en : "five o'clock", l : '会L1(e)' },
    { ja : 'ご主人|ごしゅじん', en : '(your/her) husband', l : '会L14' },
    { ja : '午前|ごぜん', en : 'A.M.', l : '会L1' },
    { ja : '午前中|ごぜんちゅう', en : 'in the morning', l : '読L9-II' },
    { ja : '答え|こたえ', en : 'answer', l : '会L11(e), 読L23-II' },
    { ja : '答える|こたえる', en : 'to answer', v : 'ru', l : '読L8-II, 会L23' },
    { ja : 'ごちそう', en : 'excellent food', l : '読L9-II' },
    { ja : 'ごちそうさま（でした）', en : 'Thank you for the meal. (after eating)', l : '会G' },
    { ja : 'ごちそうする', en : 'to treat/invite (someone) to a meal', v : 'irr', l : '会L19' },
    { ja : 'こちら', en : 'this way (polite); this person (polite)', l : '会L11, 会L18' },
    { ja : '小包|こづつみ', en : 'parcel', l : '会L5(e)' },
    { ja : '事|こと', en : 'things; matters', l : '読L11-II, 会L21' },
    { ja : '今年|ことし', en : 'this year', l : '会L4(e), 会L10' },
    { ja : '言葉|ことば', en : 'language; word(s)', l : '会L13' },
    { ja : '子供|こども', en : 'child', l : '会L4' },
    { ja : 'この', en : 'this...', l : '会L2' },
    { ja : 'この間|このあいだ', en : 'the other day', l : '会L16' },
    { ja : 'このぐらい', en : 'about this much', l : '会L16' },
    { ja : 'このごろ', en : 'these days', l : '会L10' },
    { ja : 'このように', en : 'like this; this way', l : '読L23-II' },
    { ja : 'ご飯|ごはん', en : 'rice; meal', l : '会L4' },
    { ja : 'コピーを取る|コピーをとる', en : 'to make a photocopy', v : 'u', l : '会L22' },
    { ja : '五分|ごふん', en : 'five minutes', l : '会L1(e)' },
    { ja : '困る|こまる', en : 'to have difficulty', v : 'u', l : '会L16' },
    { ja : 'ごみ', en : 'garbage', l : '会L16' },
    { ja : '込む|こむ', en : 'to get crowded', v : 'u', l : '読L13-III, 会L17' },
    { ja : 'ごめん', en : "I'm sorry. (casual)", l : '会L16' },
    { ja : 'ごめんなさい', en : "I'm sorry.", l : '会L4' },
    { ja : 'ご覧になる|ごらんになる', en : 'honorific exp. for みる', v : 'u', l : '会L19' },
    { ja : 'ゴルフ', en : 'golf', l : '会L13' },
    { ja : 'これ', en : 'this one', l : '会L2' },
    { ja : 'これから', en : 'from now on', l : '読L11-II, 会L16' },
    { ja : 'ころ', en : 'time of...; when...', l : '会L21' },
    { ja : '～ごろ', en : 'at about...', l : '会L3' },
    { ja : '転ぶ|ころぶ', en : 'to fall down', v : 'u', l : '会L18' },
    { ja : '怖い|こわい', en : 'scary; frightening', l : '会L5' },
    { ja : '壊す|こわす', en : 'to break (something)', v : 'u', l : '会L18' },
    { ja : '壊れる|こわれる', en : '(something) breaks', v : 'ru', l : '会L18' },
    { ja : '今学期|こんがっき', en : 'this semester', l : '会L11' },
    { ja : '今月|こんげつ', en : 'this month', l : '会L4(e), 会L8' },
    { ja : 'コンサート', en : 'concert', l : '会L9' },
    { ja : '今週|こんしゅう', en : 'this week', l : '会L4(e), 会L6' },
    { ja : 'コンタクト', en : 'contact lenses', l : '会L17' },
    { ja : '込んでいる|こんでいる', en : 'to be crowded', l : '読L13-III' },
    { ja : '今度|こんど', en : 'near future', l : '会L9' },
    { ja : 'こんな～', en : '...like this; this kind of...', l : '会L14' },
    { ja : 'こんなふう', en : 'like this', l : '会L22' },
    { ja : 'こんにちは', en : 'Good afternoon.', l : '会G' },
    { ja : '今晩|こんばん', en : 'tonight', l : '会L3' },
    { ja : 'こんばんは', en : 'Good evening.', l : '会G' },
    { ja : 'コンビニ', en : 'convenience store', l : '会L7' },
    { ja : 'コンピューター', en : 'computer', l : '会L1, 会L2' }
  ],
  
  'さ' : [
    { ja : 'さあ', en : 'I am not sure,...', l : '会L20' },
    { ja : 'サークル', en : 'club activity', l : '会L7' },
    { ja : 'サーフィン', en : 'surfing', l : '会L5' },
    { ja : '～歳|～さい', en : '...years old', l : '会L1, 会L1(e)' },
    { ja : '最悪|さいあく', en : 'the worst', l : '読L20-II' },
    { ja : '最近|さいきん', en : 'recently', l : '会L15' },
    { ja : '最高|さいこう', en : 'the best', l : '読L20' },
    { ja : '最後に|さいごに', en : 'finally; lastly', l : '読L8-II, 会L23' },
    { ja : '最後の～|さいごの～', en : 'last...', l : '読L23-II' },
    { ja : '最新|さいしん', en : 'the latest', l : '読L20' },
    { ja : '最初の～|さいしょの～', en : 'first...', l : '読L23-II' },
    { ja : '最低|さいてい', en : 'the lowest; the worst', l : '会L17' },
    { ja : '財布|さいふ', en : 'wallet', l : '会L2' },
    { ja : '探す|さがす', en : 'to search; to look for', v : 'u', l : '会L15' },
    { ja : '魚|さかな', en : 'fish', l : '会L2' },
    { ja : '咲く|さく', en : 'to bloom', v : 'u', l : '会L18' },
    { ja : '作品|さくひん', en : 'artistic piece', l : '読L17-II' },
    { ja : '作文|さくぶん', en : 'essay; composistion', l : '会L9' },
    { ja : '酒|さけ', en : 'sake; alcohol', l : '会L3' },
    { ja : '差し上げる|さしあげる', en : 'humble exp. for あげる', v : 'ru', l : '会L20' },
    { ja : '刺す|さす', en : 'to bite', v : 'u', l : '会L21' },
    { ja : '誘う|さそう', en : 'to invite', v : 'u', l : '会L15' },
    { ja : '～冊|～さつ', en : 'counter for bound volumes', l : '会L14, 会L14(e)' },
    { ja : '作家|さっか', en : 'writer', l : '会L11' },
    { ja : 'サッカー', en : 'soccer', l : '会L10' },
    { ja : '雑誌|ざっし', en : 'magazine', l : '会L3' },
    { ja : '砂糖|さとう', en : 'sugar', l : '会L16' },
    { ja : '寂しい|さびしい', en : 'lonely', l : '会L9' },
    { ja : 'サボる', en : 'to cut (classes)', v : 'u', l : '会L11' },
    { ja : '～様|～さま', en : 'Mr./Ms....', l : '読L5-II' },
    { ja : '寒い|さむい', en : 'cold (weather)', l : '会L5' },
    { ja : 'さようなら', en : 'Good-bye.', l : '会G' },
    { ja : '皿|さら', en : 'plate; dish', l : '会L14' },
    { ja : '再来月|さらいげつ', en : 'the month after next', l : '会L4(e)' },
    { ja : '再来週|さらいしゅう', en : 'the week after next', l : '会L4(e)' },
    { ja : '再来年|さらいねん', en : 'the year after next', l : '会L4(e)' },
    { ja : 'サラリーマン', en : 'salaryman; company employee', l : '会L17' },
    { ja : '猿|さる', en : 'monkey', l : '会L22' },
    { ja : '触る|さわる', en : 'to touch', v : 'u', l : '会L21' },
    { ja : '～さん', en : 'Mr./Ms....', l : '会L1' },
    { ja : '三月|さんがつ', en : 'March', l : '会L4(e)' },
    { ja : '残業|ざんぎょう', en : 'overtime work', l : '読L8-II, 会L17' },
    { ja : '三歳|さんさい', en : 'three years old', l : '会L1(e)' },
    { ja : '三時|さんじ', en : "three o'clock", l : '会L1(e)' },
    { ja : '三十分|さんじ(ゅ)っぷん', en : 'thirty minutes', l : '会L1(e)' },
    { ja : '賛成する|さんせいする', en : 'to agree', v : 'irr', l : '会L22' },
    { ja : '残高照会|ざんだかしょうかい', en : 'balance inquiry', l : '会L13(e)' },
    { ja : '残念（ですね）|ざんねん（ですね）', en : "That's too bad.", l : '会L8' },
    { ja : '産婦人科|さんふじんか', en : 'obstetrician and gynecologist', l : '会L12(e)' },
    { ja : '三分|さんぷん', en : 'three minutes', l : '会L1(e)' },
    { ja : '散歩する|さんぽする', en : 'to take a walk', v : 'irr', l : '会L9' }
  ],
  
  'し' : [
    
  ],
  
  'す' : [
    
  ],
  
  'せ' : [
    
  ],
  
  'そ' : [
    
  ],
  
  'た' : [
    
  ],
  
  'ち' : [
    
  ],
  
  'つ' : [
    
  ],
  
  'て' : [
    
  ],
  
  'と' : [
    
  ],
  
  'な' : [
    
  ],
  
  'に' : [
    
  ],
  
  'ぬ' : [
    
  ],
  
  'ね' : [
    
  ],
  
  'の' : [
    
  ],
  
  'は' : [
    
  ],
  
  'ひ' : [
    
  ],
  
  'ふ' : [
    
  ],
  
  'へ' : [
    
  ],
  
  'ほ' : [
    
  ],
  
  'ま' : [
    
  ],
  
  'み' : [
    
  ],
  
  'む' : [
    
  ],
  
  'め' : [
    
  ],
  
  'も' : [
    
  ],
  
  'や' : [
    
  ],
  
  'ゆ' : [
    
  ],
  
  'よ' : [
    
  ],
  
  'ら' : [
    
  ],
  
  'り' : [
    
  ],
  
  'る' : [
    
  ],
  
  'れ' : [
    
  ],
  
  'ろ' : [
    
  ],
  
  'わ' : [
    
  ]
  
};